import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const spaceTimeConfig: ComponentConfig = {
  slug: "spacetime",
  name: "Spacetime Grid",
  category: "background",
  componentPath: "app/meta/background/topographic/SpaceTime.tsx",
  npmPackageName: "@reactbytes/spacetime",
  version: "1.0.0",
  description: "A responsive topographic spacetime grid background component with mouse parallax, click warping, and custom color/glow controls.",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
  },
  showDemoByDefault: true,
  demoVariant: "text",
  props: [
    {
      name: "loopDuration",
      type: "number",
      default: 1200,
      min: 400,
      max: 3000,
      step: 50,
      description: "Speed of the infinite loop in milliseconds.",
    },
    {
      name: "strokeColor",
      type: "color",
      default: "#00e5ff",
      description: "Hex color for the neon topographic grid lines.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#020205",
      description: "Background color of the space canvas.",
    },
    {
      name: "strokeWidth",
      type: "number",
      default: 4,
      min: 1,
      max: 12,
      step: 1,
      description: "Thickness of grid lines in pixels.",
    },
    {
      name: "parallaxAmount",
      type: "number",
      default: 0.04,
      min: 0.0,
      max: 0.2,
      step: 0.01,
      description: "Intensity of 3D parallax hover effect (movement scale).",
    },
    {
      name: "warpStrength",
      type: "number",
      default: -8,
      min: -20,
      max: 20,
      step: 1,
      description: "Intensity and direction of the time-reverse click warp force.",
    },
    {
      name: "distortionScale",
      type: "number",
      default: 7,
      min: 0,
      max: 30,
      step: 1,
      description: "Wobble distortion scale applied to the topographic lines.",
    },
    {
      name: "glowIntensity",
      type: "number",
      default: 0.4,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      description: "Intensity scale (0 to 1) of drop shadows and ambient glows.",
    },
    {
      name: "noiseEnabled",
      type: "boolean",
      default: true,
      description: "Enables a static cyberpunk analog noise overlay pattern.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Spacetime Grid",
      config: {
        loopDuration: 1200,
        strokeColor: "#00e5ff",
        bgColor: "#020205",
        strokeWidth: 4,
        parallaxAmount: 0.04,
        warpStrength: -8,
        distortionScale: 7,
        glowIntensity: 0.4,
        noiseEnabled: true,
      },
    },
    {
      id: "event-horizon",
      label: "Event Horizon",
      config: {
        loopDuration: 2200,
        strokeColor: "#ff4500",
        bgColor: "#050002",
        strokeWidth: 5,
        parallaxAmount: 0.02,
        warpStrength: -18,
        distortionScale: 24,
        glowIntensity: 0.75,
        noiseEnabled: true,
      },
    },
    {
      id: "neon-matrix",
      label: "Neon Matrix",
      config: {
        loopDuration: 800,
        strokeColor: "#39ff14",
        bgColor: "#000803",
        strokeWidth: 3,
        parallaxAmount: 0.08,
        warpStrength: 12,
        distortionScale: 3,
        glowIntensity: 0.5,
        noiseEnabled: true,
      },
    },
    {
      id: "hyperdrive",
      label: "Hyperdrive",
      config: {
        loopDuration: 500,
        strokeColor: "#ff007f",
        bgColor: "#0b001a",
        strokeWidth: 2,
        parallaxAmount: 0.14,
        warpStrength: -4,
        distortionScale: 0,
        glowIntensity: 0.35,
        noiseEnabled: false,
      },
    },
    {
      id: "amber-terminal",
      label: "Amber Terminal",
      config: {
        loopDuration: 1600,
        strokeColor: "#ffb300",
        bgColor: "#100a00",
        strokeWidth: 4,
        parallaxAmount: 0.05,
        warpStrength: -11,
        distortionScale: 12,
        glowIntensity: 0.6,
        noiseEnabled: true,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
  ],
};