import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const stackedCardsConfig: ComponentConfig = {
  slug: "stacked-cards",
  name: "Stacked Cards",
  category: "miscellaneous",
  tags: ["cards", "stack", "3d", "depth", "fan"],
  componentPath: "app/meta/card/StackedCards/StackedCards.tsx",
  npmPackageName: "@reactbytes/stacked-cards",
  version: "1.0.0",
  dependencies: {},
  peerDependencies: {
    react: "^19.0.0",
    "react-dom": "^19.0.0",
  },
  containerClassName:
    "w-full !h-[500px] !block overflow-y-auto p-8 bg-zinc-950 rounded-3xl border border-white/5 relative custom-scrollbar",
  props: [
    {
      name: "textColor",
      type: "color",
      default: "#F2EEE9",
      description: "Base text color of the container.",
    },
    {
      name: "accentColor",
      type: "color",
      default: "#C0DEDD",
      description: "Accent color used for selection.",
    },
    {
      name: "stickyTop",
      type: "string",
      default: "40px",
      description: "Sticky top position for the cards.",
    },
    {
      name: "cardHeight",
      type: "string",
      default: "360px",
      description: "Height of the cards.",
    },
    {
      name: "rotationStrength",
      type: "number",
      default: 3,
      min: 0,
      max: 20,
      step: 1,
      description: "Strength of the rotation animation (degrees).",
    },
    {
      name: "scaleStrength",
      type: "number",
      default: 0.9,
      min: 0.5,
      max: 1.0,
      step: 0.01,
      description: "Scaling factor when cards stack (0 to 1).",
    },
    {
      name: "yOffset",
      type: "string",
      default: "-20px",
      description: "Vertical offset when cards stack.",
    },
    {
      name: "borderRadius",
      type: "string",
      default: "40px",
      description: "Border radius for the cards.",
    },
    {
      name: "headerText",
      type: "string",
      default: "Scroll Below",
      description: "Optional header text to display above cards.",
    },
    {
      name: "footerText",
      type: "string",
      default: "End of the sequence.",
      description: "Optional footer text to display below cards.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Standard Sequence",
      config: {
        textColor: "#F2EEE9",
        accentColor: "#C0DEDD",
        stickyTop: "40px",
        cardHeight: "360px",
        rotationStrength: 3,
        scaleStrength: 0.9,
        yOffset: "-20px",
        borderRadius: "40px",
        headerText: "Scroll Below",
        footerText: "End of the sequence.",
      },
    },
    {
      id: "minimal",
      label: "Minimal Stack",
      config: {
        textColor: "#1A1A1A",
        accentColor: "#000000",
        stickyTop: "20px",
        cardHeight: "400px",
        rotationStrength: 0,
        scaleStrength: 0.95,
        yOffset: "0px",
        borderRadius: "12px",
        headerText: "Scroll Below",
        footerText: "End of the sequence.",
      },
    },
    {
      id: "brutalist",
      label: "Brutalist Drift",
      config: {
        textColor: "#FFFFFF",
        accentColor: "#FF3E00",
        stickyTop: "60px",
        cardHeight: "320px",
        rotationStrength: 8,
        scaleStrength: 0.8,
        yOffset: "-40px",
        borderRadius: "0px",
        headerText: "Scroll Below",
        footerText: "End of the sequence.",
      },
    },
  ],
  staticProps: {
    items: [
      {
        id: "1",
        num: "01",
        label: "Architecture",
        title: "Sticky Flow",
        desc: "Leaving behind complex math for native CSS sticky positioning. The cards flow and lock into place organically.",
        bg: "#C0DEDD",
        text: "#060010",
        border: "rgba(6, 0, 16, 0.2)",
      },
      {
        id: "2",
        num: "02",
        label: "Animation",
        title: "Interpolation",
        desc: "Powered by GSAP, translating vertical scroll momentum into perfectly eased, 60fps hardware-accelerated transforms.",
        bg: "#E6DFF1",
        text: "#1D1C21",
        border: "rgba(29, 28, 33, 0.2)",
      },
      {
        id: "3",
        num: "03",
        label: "Dimension",
        title: "Z-Space Depth",
        desc: "Cards don’t just scale; they rotate on multiple axes. Alternating Z-rotations create a beautifully imperfect physical stack.",
        bg: "#181A1E",
        text: "#F2EEE9",
        border: "rgba(242, 238, 233, 0.1)",
      },
      {
        id: "4",
        num: "04",
        label: "Performance",
        title: "Composite Layer",
        desc: "By only animating transforms and filters, we bypass main-thread layout thrashing for a buttery, immersive experience.",
        bg: "#F2EEE9",
        text: "#000000",
        border: "rgba(0, 0, 0, 0.2)",
      },
    ],
  },
  credits: [
    {
      title: "Project Author",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Creator & Lead Designer",
          url: "https://github.com/ChandruMIT-o",
        },
      ],
    },
    {
      title: "Inspiration & Tech",
      items: [
        {
          name: "GSAP",
          role: "Animation Engine",
          url: "https://greensock.com/gsap/",
        },
      ],
    },
  ],
};
