import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const glowCardConfig: ComponentConfig = {
  slug: "glow-card",
  name: "Glowing Shadows",
  category: "miscellaneous",
  componentPath: "app/meta/buttons/GlowCard/GlowCard.tsx",
  containerClassName: "w-full min-h-[500px] !h-auto flex items-center justify-center p-8 bg-[#020005] rounded-[32px] border border-white/5 relative overflow-hidden",
  props: [
    {
      name: "title",
      type: "string",
      default: "Glow Card",
      description: "Text label displayed inside the card.",
    },
    {
      name: "uppercase",
      type: "boolean",
      default: false,
      description: "Whether to force content text to uppercase.",
    },
    {
      name: "animationSpeed",
      type: "number",
      default: 4,
      min: 0.5,
      max: 10.0,
      step: 0.5,
      description: "Duration of the orbital glow animation in seconds.",
    },
    {
      name: "glowBlur",
      type: "number",
      default: 6,
      min: 0,
      max: 30,
      step: 1,
      description: "Blur intensity factor for the shadow glow.",
    },
    {
      name: "glowOpacity",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Transparency of the bloom effect (0.0 to 1.0).",
    },
    {
      name: "glowScale",
      type: "number",
      default: 1.5,
      min: 1.0,
      max: 5.0,
      step: 0.2,
      description: "Size multiplier for the bloom on hover.",
    },
    {
      name: "borderRadius",
      type: "string",
      default: "2rem",
      description: "CSS border-radius value for the card.",
    },
    {
      name: "borderWidth",
      type: "number",
      default: 3,
      min: 1,
      max: 10,
      step: 1,
      description: "Thickness of the gradient border in pixels.",
    },
    {
      name: "baseColor",
      type: "color",
      default: "hsl(260deg 100% 3%)",
      description: "Background color of the card body.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Cosmic (Default)",
      config: {
        title: "Glow Card",
        uppercase: true,
        animationSpeed: 4,
        glowBlur: 6,
        glowOpacity: 1,
        glowScale: 1.5,
        borderWidth: 3,
        borderRadius: "2rem",
        baseColor: "hsl(260deg 100% 3%)",
      },
    },
    {
      id: "nuclear",
      label: "Nuclear (Fast)",
      config: {
        title: "Glow Card",
        uppercase: true,
        animationSpeed: 1,
        glowBlur: 10,
        glowOpacity: 1,
        glowScale: 2.5,
        borderWidth: 5,
        borderRadius: "1rem",
        baseColor: "hsl(120deg 100% 5%)",
      },
    },
    {
      id: "cyber",
      label: "Cyber (Sharp)",
      config: {
        title: "Glow Card",
        uppercase: true,
        animationSpeed: 2,
        glowBlur: 2,
        glowOpacity: 0.8,
        glowScale: 1.2,
        borderWidth: 1,
        borderRadius: "0.5rem",
        baseColor: "hsl(200deg 100% 2%)",
      },
    },
    {
      id: "soft",
      label: "Soft (Ghost)",
      config: {
        title: "Glow Card",
        uppercase: true,
        animationSpeed: 8,
        glowBlur: 15,
        glowOpacity: 0.5,
        glowScale: 3,
        borderWidth: 2,
        borderRadius: "3rem",
        baseColor: "hsl(280deg 40% 10%)",
      },
    },
    {
      id: "ethereal",
      label: "Ethereal (Lush)",
      config: {
        title: "Glow Card",
        uppercase: true,
        animationSpeed: 6,
        glowBlur: 8,
        glowOpacity: 0.9,
        glowScale: 2,
        borderWidth: 4,
        borderRadius: "2.5rem",
        baseColor: "hsl(320deg 80% 4%)",
      },
    },
  ],
  credits: [
    {
      title: "Inspiration",
      items: [
        {
          name: "LukyVj",
          role: "Original Design",
          url: "https://lucasbonomi.com",
        },
      ],
    },
  ],
};
