import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const dottedVortexConfig: ComponentConfig = {
  slug: "dotted-vortex",
  name: "Dotted Vortex",
  category: "background",
  tags: ["dots", "vortex", "spiral", "swirl", "rotation"],
  componentPath: "app/meta/background/dotted/DottedVortex.tsx",
  showDemoByDefault: true,
  demoVariant: "text",

  // Automated NPM Publishing Metadata
  npmPackageName: "@reactbytes/dotted-vortex",
  version: "1.0.0",
  description: "An interactive, high-performance canvas background component featuring a responsive point-mesh vortex that scales and twists to reveal a custom underlying image on interaction.",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
  },

  props: [
    {
      name: "imageSrc",
      type: "string",
      default: "https://images.unsplash.com/photo-1614851099511-773084f6911d?q=80&w=2564&auto=format&fit=crop",
      description: "The high-resolution background image to dynamically load and reveal.",
    },
    {
      name: "isExcited",
      type: "boolean",
      default: false,
      description: "Trigger the vortex/aperture focus state.",
    },
    {
      name: "gridSpacing",
      type: "number",
      default: 24,
      min: 10,
      max: 50,
      step: 1,
      description: "The distance between each dot in the grid.",
    },
    {
      name: "baseDotRadius",
      type: "number",
      default: 1.5,
      min: 0.5,
      max: 5.0,
      step: 0.1,
      description: "The base radius of each dot.",
    },
    {
      name: "cursorFollowSpeed",
      type: "number",
      default: 0.08,
      min: 0.01,
      max: 1.0,
      step: 0.01,
      description: "How quickly the effect follows the cursor.",
    },
    {
      name: "revealRadiusScale",
      type: "number",
      default: 0.2,
      min: 0.05,
      max: 0.5,
      step: 0.05,
      description: "The maximum distance of the reveal effect relative to screen width.",
    },
    {
      name: "kineticEnergyMultiplier",
      type: "number",
      default: 0.4,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "How intensely the cursor speed injects kinetic energy into dots.",
    },
    {
      name: "rippleSpeed",
      type: "number",
      default: 10,
      min: 1,
      max: 20,
      step: 1,
      description: "The radius expansion speed of click ripples.",
    },
    {
      name: "twistAngle",
      type: "number",
      default: 2.51,
      min: 0,
      max: 6.28,
      step: 0.1,
      description: "The maximum rotation angle when in the excited state.",
    },
    {
      name: "apertureSize",
      type: "number",
      default: 0.12,
      min: 0.05,
      max: 0.5,
      step: 0.05,
      description: "The size of the aperture focal point when excited.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#0a0a0a",
      description: "The solid background color beneath everything.",
    },
    {
      name: "activeDotColor",
      type: "color",
      default: "#ffffff",
      description: "The color of the active interactive dots.",
    },
    {
      name: "idleDotColor",
      type: "string",
      default: "rgba(255, 255, 255, 0.15)",
      description: "The color of the distant, un-scaled dots.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Vortex",
      config: {
        bgColor: "#0a0a0a",
        activeDotColor: "#ffffff",
        idleDotColor: "rgba(255, 255, 255, 0.15)",
        gridSpacing: 24,
        baseDotRadius: 1.5,
        cursorFollowSpeed: 0.08,
        revealRadiusScale: 0.2,
        kineticEnergyMultiplier: 0.4,
        rippleSpeed: 10,
        twistAngle: 2.51,
        apertureSize: 0.12,
      },
    },
    {
      id: "matrix",
      label: "Digital Matrix",
      config: {
        bgColor: "#000500",
        activeDotColor: "#00ff41",
        idleDotColor: "rgba(0, 255, 65, 0.1)",
        gridSpacing: 20,
        baseDotRadius: 1.2,
        cursorFollowSpeed: 0.1,
        revealRadiusScale: 0.25,
        kineticEnergyMultiplier: 0.8,
        rippleSpeed: 12,
        twistAngle: 3.14,
        apertureSize: 0.15,
      },
    },
    {
      id: "dense",
      label: "Dense Fabric",
      config: {
        bgColor: "#111111",
        activeDotColor: "#ff0055",
        idleDotColor: "rgba(255, 0, 85, 0.05)",
        gridSpacing: 12,
        baseDotRadius: 1.0,
        cursorFollowSpeed: 0.05,
        revealRadiusScale: 0.15,
        kineticEnergyMultiplier: 0.2,
        rippleSpeed: 5,
        twistAngle: 1.5,
        apertureSize: 0.1,
      },
    },
    {
      id: "fluid",
      label: "Fluid Motion",
      config: {
        bgColor: "#000011",
        activeDotColor: "#00ffff",
        idleDotColor: "rgba(0, 255, 255, 0.2)",
        gridSpacing: 30,
        baseDotRadius: 2.5,
        cursorFollowSpeed: 0.2,
        revealRadiusScale: 0.3,
        kineticEnergyMultiplier: 1.2,
        rippleSpeed: 15,
        twistAngle: 6.28,
        apertureSize: 0.2,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
  ],
};