import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const eyeMatrixConfig: ComponentConfig = {
  slug: "eye-matrix",
  name: "Eye Matrix",
  category: "background",
  tags: ["eye", "matrix", "dots", "grid", "gaze", "pattern"],
  componentPath: "app/meta/background/dotted/EyeMatrix.tsx",
  npmPackageName: "@reactbytes/eye-matrix",
  version: "1.0.0",
  description: "An interactive background grid component of wiggling eyes that follow mouse coordinates with organic blinking, spring physics, and packed layouts.",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
  },
  showDemoByDefault: true,
  demoVariant: "card",
  props: [
    {
      name: "paletteKey",
      type: "select",
      default: "monochromeDark",
      options: [
        { id: "monochromeDark", label: "Noir Slate" },
        { id: "monochromeLight", label: "Ghostly Silver" },
        { id: "monochromeMixed", label: "High Contrast Grey" },
      ],
      description: "Flat monochrome color profile configuration.",
    },
    {
      name: "interactiveMode",
      type: "select",
      default: "mouse",
      options: [
        { id: "mouse", label: "Mouse Tracker" },
        { id: "wander", label: "Organic Wander" },
        { id: "vortex", label: "Vortex Spin" },
      ],
      description: "Target tracking mode of the eyeballs.",
    },
    {
      name: "pupilStyle",
      type: "select",
      default: "normal",
      options: [
        { id: "normal", label: "Normal" },
        { id: "cat", label: "Cat Eye" },
        { id: "sparkle", label: "Sparkle" },
        { id: "ring", label: "Ring" },
      ],
      description: "Visual shape geometry style of the pupil.",
    },
    {
      name: "eyeCount",
      type: "number",
      default: 180,
      min: 10,
      max: 350,
      step: 5,
      description: "Number of packed eye nodes in the viewport grid.",
    },
    {
      name: "padding",
      type: "number",
      default: 4.0,
      min: 0.0,
      max: 16.0,
      step: 0.5,
      description:
        "Horizontal/vertical spacing offset separating neighboring nodes.",
    },
    {
      name: "minRadius",
      type: "number",
      default: 12,
      min: 4,
      max: 40,
      step: 1,
      description: "Minimum radius limit of randomly generated eye circles.",
    },
    {
      name: "maxRadius",
      type: "number",
      default: 65,
      min: 20,
      max: 180,
      step: 2,
      description: "Maximum radius limit of randomly generated eye circles.",
    },
    {
      name: "scleraScale",
      type: "number",
      default: 0.65,
      min: 0.2,
      max: 0.85,
      step: 0.01,
      description: "Scale of the white eyeball globe relative to node size.",
    },
    {
      name: "pupilScale",
      type: "number",
      default: 0.45,
      min: 0.15,
      max: 0.8,
      step: 0.01,
      description: "Scale of the pupil iris relative to eyeball size.",
    },
    {
      name: "physicsStiffness",
      type: "number",
      default: 0.12,
      min: 0.01,
      max: 0.4,
      step: 0.01,
      description: "Stiffness tension factor of the spring wiggling.",
    },
    {
      name: "physicsDamping",
      type: "number",
      default: 0.78,
      min: 0.4,
      max: 0.95,
      step: 0.01,
      description: "Friction resistance damping of pupil inertia wiggles.",
    },
    {
      name: "blinkingEnabled",
      type: "boolean",
      default: true,
      description: "Toggles organic blinking behavior.",
    },
    {
      name: "blinkRate",
      type: "number",
      default: 0.015,
      min: 0.005,
      max: 0.1,
      step: 0.005,
      description:
        "Probability threshold of triggering close eyelids on each frame loop.",
    },
    {
      name: "flatBorderEnabled",
      type: "boolean",
      default: true,
      description: "Renders solid outlines around eye body structures.",
    },
    {
      name: "customBg",
      type: "string",
      default: "",
      description: "Hex override for the background layer.",
    },
  ],
  presets: [
    {
      id: "monochromeDark",
      label: "Noir Slate (Dark)",
      config: {
        eyeCount: 180,
        padding: 4,
        minRadius: 12,
        maxRadius: 65,
        paletteKey: "monochromeDark",
        customBg: "",
        scleraScale: 0.65,
        pupilScale: 0.45,
        pupilStyle: "normal",
        physicsStiffness: 0.12,
        physicsDamping: 0.78,
        blinkingEnabled: true,
        blinkRate: 0.015,
        interactiveMode: "mouse",
        flatBorderEnabled: true,
      },
    },
    {
      id: "monochromeLight",
      label: "Ghostly Silver (Light)",
      config: {
        eyeCount: 150,
        padding: 3,
        minRadius: 10,
        maxRadius: 55,
        paletteKey: "monochromeLight",
        customBg: "",
        scleraScale: 0.7,
        pupilScale: 0.5,
        pupilStyle: "cat",
        physicsStiffness: 0.15,
        physicsDamping: 0.82,
        blinkingEnabled: true,
        blinkRate: 0.02,
        interactiveMode: "wander",
        flatBorderEnabled: true,
      },
    },
    {
      id: "monochromeMixed",
      label: "High Contrast Grey",
      config: {
        eyeCount: 200,
        padding: 5,
        minRadius: 15,
        maxRadius: 70,
        paletteKey: "monochromeMixed",
        customBg: "",
        scleraScale: 0.6,
        pupilScale: 0.4,
        pupilStyle: "sparkle",
        physicsStiffness: 0.1,
        physicsDamping: 0.75,
        blinkingEnabled: true,
        blinkRate: 0.01,
        interactiveMode: "vortex",
        flatBorderEnabled: true,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
  ],
};
