import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const magneticDotMeshConfig: ComponentConfig = {
  slug: "magnetic-dots",
  name: "Magnetic Dot Mesh",
  category: "background",
  tags: ["magnetic", "dots", "mesh", "interactive", "mouse", "grid"],
  componentPath: "app/meta/background/dotted/MagneticDotMesh.tsx",
  showDemoByDefault: true,
  npmPackageName: "@reactbytes/magnetic-dots",
  version: "1.0.0",
  description: "An interactive, physics-based canvas component featuring a mesh of dots that react to mouse movement and click-triggered shockwaves.",
  dependencies: {
    "react-use-measure": "^2.1.1"
  },
  peerDependencies: {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  props: [
    {
      name: "gap",
      type: "number",
      default: 80,
      min: 20,
      max: 120,
      step: 2,
      description: "Grid spacing between dots.",
    },
    {
      name: "dotRadius",
      type: "number",
      default: 2,
      min: 1,
      max: 10,
      step: 0.5,
      description: "Resting size of each dot.",
    },
    {
      name: "repelRadius",
      type: "number",
      default: 250,
      min: 50,
      max: 400,
      step: 10,
      description: "Radius of mouse repulsion influence.",
    },
    {
      name: "repelForce",
      type: "number",
      default: 30,
      min: 1,
      max: 50,
      step: 1,
      description: "Strength of the mouse repulsion push.",
    },
    {
      name: "springStiffness",
      type: "number",
      default: 0.055,
      min: 0.005,
      max: 0.2,
      step: 0.005,
      description:
        "Stiffness of the spring pulling dots back to home positions.",
    },
    {
      name: "damping",
      type: "number",
      default: 0.82,
      min: 0.5,
      max: 0.99,
      step: 0.01,
      description: "Velocity decay factor (friction).",
    },
    {
      name: "lineDist",
      type: "number",
      default: 150,
      min: 10,
      max: 200,
      step: 5,
      description: "Max distance for connecting dots with mesh lines.",
    },
    {
      name: "shockwaveDist",
      type: "number",
      default: 220,
      min: 50,
      max: 500,
      step: 10,
      description: "Reach of the shockwave after a click.",
    },
    {
      name: "shockwaveForce",
      type: "number",
      default: 22,
      min: 1,
      max: 100,
      step: 1,
      description: "Strength of the shockwave push.",
    },
    {
      name: "color1",
      type: "color",
      default: "#ffffff",
      description: "Primary color for resting dots.",
    },
    {
      name: "color2",
      type: "color",
      default: "#e1e1e1",
      description: "Secondary color for displaced dots.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Loose Connections",
      config: {
        gap: 80,
        dotRadius: 2,
        repelRadius: 250,
        repelForce: 30,
        springStiffness: 0.055,
        damping: 0.82,
        lineDist: 150,
        shockwaveDist: 220,
        shockwaveForce: 22,
        color1: "#ffffffff",
        color2: "#e1e1e1",
      },
    },
    {
      id: "normal",
      label: "Normal Mesh",
      config: {
        gap: 48,
        dotRadius: 2,
        repelRadius: 140,
        repelForce: 14,
        springStiffness: 0.055,
        damping: 0.82,
        lineDist: 70,
        shockwaveDist: 220,
        shockwaveForce: 22,
        color1: "#7c5cff",
        color2: "#2ee6a6",
      },
    },
    {
      id: "dense",
      label: "Dense Network",
      config: {
        gap: 25,
        dotRadius: 2,
        repelRadius: 100,
        repelForce: 8,
        springStiffness: 0.055,
        damping: 0.82,
        lineDist: 45,
        shockwaveDist: 220,
        shockwaveForce: 22,
        color1: "#3b82f6",
        color2: "#60a5fa",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
    {
      title: "Inspiration",
      items: [
        {
          name: "JP Belley",
          role: "Designer",
          url: "https://jeanphilippebelley.com/",
        },
      ],
    },
  ],
};
