import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const poissonNoiseConfig: ComponentConfig = {
  slug: "poisson-noise",
  name: "Poisson Disc Noise",
  category: "background",
  tags: ["poisson", "noise", "scatter", "dots", "distribution"],
  componentPath: "app/meta/background/dotted/PoissonNoise.tsx",
  showDemoByDefault: true,
  demoVariant: "hero",
  props: [
    {
      name: "renderMode",
      type: "select",
      default: "dots",
      options: [
        { id: "dots", label: "Nodes (Dots)" },
        { id: "circles", label: "Pack Circles" },
        { id: "constellation", label: "Constellation" },
        { id: "hybrid", label: "Hybrid View" },
      ],
      description:
        "The aesthetic representation style of the particles or grid structures.",
    },
    {
      name: "colorTheme",
      type: "select",
      default: "monochrome",
      options: [
        { id: "monochrome", label: "Pure Monochrome" },
        { id: "solarized", label: "Solar Amber" },
        { id: "nebula", label: "Deep Nebula" },
        { id: "cyberpunk", label: "Cyber Neon" },
      ],
      description:
        "Curated harmonious color palette preset applied to render elements.",
    },
    {
      name: "mouseInfluence",
      type: "select",
      default: "repel",
      options: [
        { id: "repel", label: "Repel Particles" },
        { id: "attract", label: "Attract Particles" },
        { id: "scaleUp", label: "Scale Up Size" },
        { id: "scaleDown", label: "Scale Down Size" },
        { id: "none", label: "No Influence" },
      ],
      description:
        "How the pointer alters particle positioning or local scaling.",
    },
    {
      name: "minRadius",
      type: "number",
      default: 6,
      min: 4,
      max: 15,
      step: 1,
      description: "Minimum particle exclusion/spacing radius.",
    },
    {
      name: "maxRadius",
      type: "number",
      default: 35,
      min: 16,
      max: 65,
      step: 1,
      description: "Maximum particle exclusion/spacing radius.",
    },
    {
      name: "maxParticles",
      type: "number",
      default: 800,
      min: 200,
      max: 1200,
      step: 50,
      description: "Upper limit of active particles on screen.",
    },
    {
      name: "noiseScale",
      type: "number",
      default: 0.003,
      min: 0.001,
      max: 0.01,
      step: 0.0005,
      description: "Zoom level/frequency of the 2D gradient noise field.",
    },
    {
      name: "noiseStrength",
      type: "number",
      default: 1.8,
      min: 0.5,
      max: 5.0,
      step: 0.1,
      description:
        "Force strength of the noise field applied to particle velocities.",
    },
    {
      name: "driftSpeed",
      type: "number",
      default: 0.015,
      min: 0.001,
      max: 0.05,
      step: 0.001,
      description: "Evolution rate/speed of the vector field over time.",
    },
    {
      name: "mouseRadius",
      type: "number",
      default: 180,
      min: 50,
      max: 400,
      step: 10,
      description: "Exclusion/attraction zone radius around the cursor.",
    },
    {
      name: "mouseIntensity",
      type: "number",
      default: 1.0,
      min: 0.1,
      max: 3.0,
      step: 0.1,
      description:
        "Force strength / intensity multiplier of the cursor interaction.",
    },
    {
      name: "isPlaying",
      type: "boolean",
      default: true,
      description: "Whether the animation loop is running or paused.",
    },
  ],
  presets: [
    {
      id: "constellation",
      label: "Stellar",
      config: {
        renderMode: "constellation",
        colorTheme: "cyberpunk",
        minRadius: 12,
        maxRadius: 40,
        noiseScale: 0.003,
        noiseStrength: 2.5,
        driftSpeed: 0.02,
        maxParticles: 800,
        mouseInfluence: "attract",
        mouseRadius: 220,
        mouseIntensity: 1.2,
        isPlaying: true,
      },
    },
    {
      id: "cellular",
      label: "Cellular",
      config: {
        renderMode: "circles",
        colorTheme: "nebula",
        minRadius: 5,
        maxRadius: 25,
        noiseScale: 0.003,
        noiseStrength: 1.5,
        driftSpeed: 0.01,
        maxParticles: 800,
        mouseInfluence: "repel",
        mouseRadius: 140,
        mouseIntensity: 1.0,
        isPlaying: true,
      },
    },
    {
      id: "hyperforce",
      label: "Hyper Force",
      config: {
        renderMode: "hybrid",
        colorTheme: "solarized",
        minRadius: 8,
        maxRadius: 35,
        noiseScale: 0.003,
        noiseStrength: 3.0,
        driftSpeed: 0.025,
        maxParticles: 800,
        mouseInfluence: "repel",
        mouseRadius: 250,
        mouseIntensity: 1.8,
        isPlaying: true,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "Poisson Disc Noise Engine",
          role: "Visual Simulation",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Library",
          url: "https://react.dev",
        },
        {
          name: "Canvas API",
          role: "Rendering Engine",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API",
        },
      ],
    },
  ],
};
