export const registryKeys = [
  // General items
  "intro",
  "install",
  "changelog",
  "admin",
  "mcp",
  "favorites",
  "components",

  // Text items
  "blur-text",
  "fall-down",
  "reveal-under",
  "variable-weight",
  "focal-blur",
  "magnetic-text",
  "shatter-text",
  "gooey-morph",
  "elastic-reveal",
  "scramble-reveal",
  "keyboard-text",
  "swarm-text",
  "volumetric-text",
  "kinetic-text",
  "granular-text",
  "tectonic-lattice",
  "stratum-text",
  "aperture-text",
  "helix-text",
  "phase-shell-text",
  "scaffold-text",
  "tectonic-track-text",
  "axial-shear-text",

  // Background items
  "atmospheric-drift",
  "ascii-wave",
  "magnetic-dots",
  "bubble-gradient",
  "fractal-background",
  "cellular-automata",
  "hive-mind",
  "helon-braid",
  "perlin-smoke",
  "metallic-twirl",
  "liquid-noise",
  "velvet-noise",
  "fbm-noise",
  "eye-matrix",
  "poisson-noise",
  "liquid-grid",
  "iridescent-gradient",
  "kaleidoscopic",
  "dotted-vortex",
  "concentric-waves",
  "ripple",
  "black-hole",
  "singularity",
  "spacetime",
  "dither",
  "petal-wave",
  "void-orb",
  "warp-speed",
  "scroll-warp",
  "superstructure",
  "stripe-flow",

  // Carousel items
  "docked-carousel",
  "stacked-carousel",
  "stacked-card-carousel",
  "void-carousel",
  "rotary-carousel",
  "morph-carousel",
  "split-carousel",
  "list-carousel",
  "interlocking-marquee",
  "dither-carousel",

  // Miscellaneous items
  "standard-accordion",
  "glow-card",
  "shiny-button",
  "vertical-menu",
  "holo-card",
  "stacked-cards",
  "sliding-menu",
  "pill-tabbed-section",
  "endless-motion-footer",
  "malakor-singularity",

  // Cursors items
  "follow-cursor",
];
