import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const dockedCarouselConfig: ComponentConfig = {
  slug: "docked-carousel",
  name: "Docked Carousel",
  category: "carousel",
  componentPath: "app/meta/carousel/DockedCarousel/DockedCarousel.tsx",
  containerClassName: "rounded-[32px] border border-white/5 bg-black shadow-2xl min-h-[500px] !h-auto !p-0",
  props: [
    {
      name: "animationType",
      type: "select",
      default: "expand",
      options: [
        { id: "expand", label: "Expansion" },
        { id: "slide", label: "Cinematic Slide" },
        { id: "pop", label: "Elastic Pop" },
      ],
      description: "The transition effect when changing images.",
    },
    {
      name: "shape",
      type: "select",
      default: "circle",
      options: [
        { id: "circle", label: "Circular" },
        { id: "square", label: "Sharp Square" },
        { id: "rectangle", label: "Rounded Rect" },
      ],
      description: "The border-radius style of the thumbnails.",
    },
    {
      name: "color",
      type: "color",
      default: "#FFFFFF",
      description: "Color for navigation arrows and the timer progress border.",
    },
    {
      name: "autoSlide",
      type: "boolean",
      default: true,
      description: "Whether the carousel should automatically cycle through images.",
    },
    {
      name: "autoSlideInterval",
      type: "number",
      default: 5000,
      min: 1000,
      max: 10000,
      step: 500,
      description: "Time in milliseconds between auto-slides.",
    },
    {
      name: "equalSize",
      type: "boolean",
      default: false,
      description: "If true, all thumbnails will have the same width instead of the dynamic dock effect.",
    },
    {
      name: "showArrows",
      type: "boolean",
      default: true,
      description: "Toggle visibility of navigation arrows.",
    },
    {
      name: "showTimer",
      type: "boolean",
      default: true,
      description: "Show the progress border on the active thumbnail.",
    },
    {
      name: "stiffness",
      type: "number",
      default: 200,
      min: 50,
      max: 1000,
      step: 10,
      description: "Spring stiffness for pop and expand animations.",
    },
    {
      name: "damping",
      type: "number",
      default: 25,
      min: 10,
      max: 100,
      step: 1,
      description: "Spring damping for pop and expand animations.",
    },
    {
      name: "transitionDuration",
      type: "number",
      default: 1.2,
      min: 0.5,
      max: 3.0,
      step: 0.1,
      description: "Duration of the slide animation in seconds.",
    },
    {
      name: "showTooltip",
      type: "boolean",
      default: false,
      description: "Show a tooltip with the item index on hover.",
    },
  ],
  presets: [
    {
      id: "interactive-expansion",
      label: "Interactive Expansion (Default)",
      config: {
        animationType: "expand",
        shape: "circle",
        stiffness: 200,
        damping: 25,
        autoSlide: true,
        equalSize: false,
        showArrows: true,
        showTimer: true,
        autoSlideInterval: 5000,
        color: "#FFFFFF",
        transitionDuration: 1.2,
        showTooltip: false,
      },
    },
    {
      id: "cinematic-glide",
      label: "Cinematic Glide",
      config: {
        animationType: "slide",
        shape: "rectangle",
        transitionDuration: 1.5,
        equalSize: true,
        autoSlide: false,
        stiffness: 200,
        damping: 25,
        showArrows: true,
        showTimer: false,
        autoSlideInterval: 5000,
        color: "#60a5fa",
        showTooltip: false,
      },
    },
    {
      id: "pop-minimalist",
      label: "Pop Minimalist",
      config: {
        animationType: "pop",
        shape: "circle",
        stiffness: 400,
        damping: 30,
        autoSlide: true,
        autoSlideInterval: 3000,
        equalSize: false,
        showArrows: true,
        showTimer: true,
        color: "#f472b6",
        transitionDuration: 1.2,
        showTooltip: false,
      },
    },
    {
      id: "static-grid",
      label: "Static Grid",
      config: {
        animationType: "expand",
        shape: "square",
        equalSize: true,
        showArrows: false,
        showTimer: false,
        autoSlide: false,
        stiffness: 200,
        damping: 25,
        autoSlideInterval: 5000,
        color: "#fbbf24",
        transitionDuration: 1.2,
        showTooltip: false,
      },
    },
    {
      id: "fast-tempo",
      label: "Fast Tempo",
      config: {
        animationType: "pop",
        shape: "circle",
        autoSlideInterval: 2000,
        stiffness: 500,
        damping: 20,
        autoSlide: true,
        equalSize: false,
        showArrows: true,
        showTimer: true,
        color: "#4ade80",
        transitionDuration: 1.2,
        showTooltip: false,
      },
    },
  ],
  credits: [
    {
      title: "Libraries",
      items: [
        {
          name: "Framer Motion",
          url: "https://www.framer.com/motion/",
          role: "Animation Engine",
        },
        {
          name: "Lucide React",
          url: "https://lucide.dev/",
          role: "Icon System",
        },
      ],
    },
    {
      title: "Project Author",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Creator & Lead Designer",
          url: "https://github.com/ChandruMIT-o",
        },
      ],
    },
    {
      title: "Core Stack",
      items: [
        {
          name: "Next.js 16",
          role: "Framework",
          url: "https://nextjs.org",
        },
        {
          name: "Tailwind CSS v4",
          role: "Styling Engine",
          url: "https://tailwindcss.com",
        },
        {
          name: "Framer Motion",
          role: "Animation Library",
          url: "https://framer.com/motion",
        },
      ],
    },
  ],
};
