import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const standardAccordionConfig: ComponentConfig = {
  slug: "standard-accordion",
  name: "Standard Accordion",
  category: "miscellaneous",
  tags: ["accordion", "faq", "collapse", "expand", "sections"],
  componentPath: "app/meta/misc/StandardAccordion/StandardAccordion.tsx",
  containerClassName:
    "w-full min-h-[550px] !h-auto flex items-center justify-center p-8 rounded-[32px] border border-white/5 bg-[#030008] shadow-2xl relative overflow-hidden",
  props: [
    {
      name: "stiffness",
      type: "number",
      default: 250,
      min: 50,
      max: 800,
      step: 10,
      description:
        "Stiffness of the spring. Higher values make the movement snappier.",
    },
    {
      name: "damping",
      type: "number",
      default: 30,
      min: 5,
      max: 100,
      step: 1,
      description:
        "Strength of opposing force. Lower values create more 'bounce'.",
    },
    {
      name: "mass",
      type: "number",
      default: 1.0,
      min: 0.1,
      max: 3.0,
      step: 0.1,
      description:
        "The weight of the moving object. Higher mass feels heavier and slower.",
    },
    {
      name: "floatOffset",
      type: "number",
      default: 24,
      min: 0,
      max: 80,
      step: 1,
      description:
        "The vertical distance items float away when an adjacent item expands.",
    },
    {
      name: "hoverScale",
      type: "number",
      default: 1.01,
      min: 1.0,
      max: 1.1,
      step: 0.005,
      description: "The scale multiplier applied to items on hover.",
    },
    {
      name: "allowMultiple",
      type: "boolean",
      default: false,
      description:
        "If true, multiple accordion items can be open simultaneously.",
    },
    {
      name: "uppercase",
      type: "boolean",
      default: false,
      description: "If true, transforms item titles to uppercase.",
    },
    {
      name: "backgroundColorOpen",
      type: "color",
      default: "#181A1E",
      description: "Background color of the accordion item when it is open.",
    },
    {
      name: "backgroundColorClosed",
      type: "color",
      default: "#060010",
      description: "Background color of the accordion item when it is closed.",
    },
    {
      name: "titleColor",
      type: "color",
      default: "#FFFFFF",
      description: "Color of the title and icon.",
    },
    {
      name: "contentColor",
      type: "color",
      default: "#A1A1AA",
      description: "Color of the expanded content text.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Refined (Balanced)",
      config: {
        stiffness: 250,
        damping: 30,
        mass: 1,
        floatOffset: 24,
        hoverScale: 1.01,
        backgroundColorOpen: "#181A1E",
        backgroundColorClosed: "#060010",
        titleColor: "#FFFFFF",
        contentColor: "#A1A1AA",
        allowMultiple: false,
        uppercase: false,
      },
    },
    {
      id: "snappy",
      label: "Snappy (High Energy)",
      config: {
        stiffness: 500,
        damping: 25,
        mass: 0.5,
        floatOffset: 16,
        hoverScale: 1.02,
        backgroundColorOpen: "#1e1b4b",
        backgroundColorClosed: "#0a0a1a",
        titleColor: "#818cf8",
        contentColor: "#c7d2fe",
        allowMultiple: false,
        uppercase: false,
      },
    },
    {
      id: "liquid",
      label: "Liquid (Smooth)",
      config: {
        stiffness: 100,
        damping: 40,
        mass: 2,
        floatOffset: 32,
        hoverScale: 1.0,
        backgroundColorOpen: "#064e3b",
        backgroundColorClosed: "#022c22",
        titleColor: "#34d399",
        contentColor: "#a7f3d0",
        allowMultiple: false,
        uppercase: false,
      },
    },
    {
      id: "dramatic",
      label: "Dramatic (Impact)",
      config: {
        stiffness: 300,
        damping: 15,
        mass: 1.5,
        floatOffset: 48,
        hoverScale: 1.03,
        backgroundColorOpen: "#451a03",
        backgroundColorClosed: "#1c0a00",
        titleColor: "#fbbf24",
        contentColor: "#fde68a",
        allowMultiple: false,
        uppercase: false,
      },
    },
    {
      id: "minimal",
      label: "Minimal (Subtle)",
      config: {
        stiffness: 150,
        damping: 30,
        mass: 1,
        floatOffset: 8,
        hoverScale: 1.005,
        backgroundColorOpen: "#18181b",
        backgroundColorClosed: "#09090b",
        titleColor: "#fafafa",
        contentColor: "#71717a",
        allowMultiple: false,
        uppercase: false,
      },
    },
  ],
  credits: [
    {
      title: "Inspiration",
      items: [
        {
          name: "Build Your Own Craft",
          role: "Design Concept",
          url: "https://buildyourowncraft.com",
        },
      ],
    },
    {
      title: "Project",
      items: [
        {
          name: "React Bytes",
          role: "Component Collection",
          url: "https://reactbytes.dev",
        },
      ],
    },
  ],
};
