import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const cellularAutomataConfig: ComponentConfig = {
  slug: "cellular-automata",
  name: "Cellular Automata",
  category: "background",
  componentPath: "app/meta/background/cellular/CellularAutomataBackground.tsx",
  props: [
    {
      name: "colorA",
      type: "color",
      default: "#050812",
      description: "Background/Void color stop.",
    },
    {
      name: "colorB",
      type: "color",
      default: "#1e1b4b",
      description: "Mid-tone energy color.",
    },
    {
      name: "colorC",
      type: "color",
      default: "#818cf8",
      description: "Highlight/Strand color.",
    },
    {
      name: "speed",
      type: "number",
      default: 0.5,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "Velocity of the energy flow.",
    },
    {
      name: "scale",
      type: "number",
      default: 1.0,
      min: 0.5,
      max: 3.0,
      step: 0.1,
      description: "Zoom level of the noise patterns. Higher values show more detail.",
    },
    {
      name: "intensity",
      type: "number",
      default: 1.0,
      min: 0.5,
      max: 2.0,
      step: 0.1,
      description: "Global brightness multiplier.",
    },
    {
      name: "opacity",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Transparency of the energy flow (0.0 to 1.0).",
    },
    {
      name: "vignetteIntensity",
      type: "number",
      default: 0.6,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Intensity of the dark edges (0.0 to 1.0).",
    },
    {
      name: "blurAmount",
      type: "number",
      default: 0,
      min: 0,
      max: 20,
      step: 1,
      description: "CSS blur radius applied to the canvas.",
    },
  ],
  presets: [
    {
      id: "electric-silk",
      label: "Electric Silk",
      config: {
        colorA: "#050812",
        colorB: "#1e1b4b",
        colorC: "#818cf8",
        speed: 0.5,
        scale: 1.0,
        intensity: 1.2,
        opacity: 1.0,
        vignetteIntensity: 0.6,
        blurAmount: 0,
      },
    },
    {
      id: "solar-winds",
      label: "Solar Winds",
      config: {
        colorA: "#0c0202",
        colorB: "#78350f",
        colorC: "#fbbf24",
        speed: 0.8,
        scale: 1.5,
        intensity: 1.3,
        opacity: 1.0,
        vignetteIntensity: 0.6,
        blurAmount: 0,
      },
    },
    {
      id: "deep-ocean",
      label: "Deep Ocean",
      config: {
        colorA: "#020808",
        colorB: "#0e7490",
        colorC: "#2dd4bf",
        speed: 0.3,
        scale: 0.8,
        intensity: 1.1,
        opacity: 1.0,
        vignetteIntensity: 0.6,
        blurAmount: 0,
      },
    },
    {
      id: "ethereal-mist",
      label: "Ethereal Mist",
      config: {
        colorA: "#0a0a0a",
        colorB: "#262626",
        colorC: "#ffffff",
        speed: 0.1,
        scale: 2.0,
        intensity: 0.9,
        opacity: 1.0,
        vignetteIntensity: 0.6,
        blurAmount: 0,
      },
    },
  ],
  credits: [
    {
      title: "Mathematical Foundations",
      items: [
        {
          name: "Simplex Noise",
          role: "Algorithm",
          url: "https://en.wikipedia.org/wiki/Simplex_noise",
        },
        {
          name: "Ken Perlin",
          role: "Core Concept",
          url: "https://mrl.cs.nyu.edu/~perlin/",
        },
      ],
    },
    {
      title: "Project",
      items: [
        {
          name: "React Bytes",
          role: "Component Collection",
          url: "https://reactbytes.dev",
        },
      ],
    },
  ],
};
