import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const granularTextConfig: ComponentConfig = {
  slug: "granular-text",
  name: "Granular Sand Text",
  category: "text",
  componentPath: "app/meta/text/Interactive/GranularText.tsx",
  props: [
    {
      name: "text",
      type: "string",
      default: "MORPH",
      description: "The word/text to render and animate.",
    },
    {
      name: "radius",
      type: "number",
      default: 65,
      min: 20,
      max: 200,
      step: 5,
      description: "Radius around mouse where particles are affected.",
    },
    {
      name: "force",
      type: "number",
      default: 7,
      min: 1,
      max: 20,
      step: 0.5,
      description: "Strength of dispersion force.",
    },
    {
      name: "gravity",
      type: "number",
      default: 0.35,
      min: 0.05,
      max: 2.0,
      step: 0.05,
      description: "Gravity/downward acceleration on particles.",
    },
    {
      name: "cooldown",
      type: "number",
      default: 100,
      min: 10,
      max: 300,
      step: 10,
      description: "Cooldown time in frames before recall starts.",
    },
    {
      name: "recallSpeed",
      type: "number",
      default: 0.14,
      min: 0.01,
      max: 0.5,
      step: 0.01,
      description: "Speed of snap-back recall.",
    },
    {
      name: "color",
      type: "color",
      default: "#ffffff",
      description: "Foreground color of the stable vector text.",
    },
    {
      name: "activeColorHex",
      type: "color",
      default: "#f59e0b",
      description: "Particle dispersion active color (hex).",
    },
    {
      name: "recallColorHex",
      type: "color",
      default: "#3b82f6",
      description: "Particle recall color (hex).",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Style",
      config: {
        text: "MORPH",
        radius: 65,
        force: 7,
        gravity: 0.35,
        cooldown: 100,
        recallSpeed: 0.14,
        color: "#ffffff",
        activeColorHex: "#f59e0b",
        recallColorHex: "#3b82f6",
      },
    },
    {
      id: "gold",
      label: "Golden Dispersion",
      config: {
        text: "GOLD",
        radius: 80,
        force: 10,
        gravity: 0.2,
        cooldown: 150,
        recallSpeed: 0.08,
        color: "#ffd700",
        activeColorHex: "#ffd700",
        recallColorHex: "#ff8c00",
      },
    },
    {
      id: "crash",
      label: "High Gravity Collapse",
      config: {
        text: "CRASH",
        radius: 100,
        force: 12,
        gravity: 0.8,
        cooldown: 60,
        recallSpeed: 0.25,
        color: "#ef4444",
        activeColorHex: "#f59e0b",
        recallColorHex: "#ffffff",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "React Bytes",
          role: "Collection",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Framework",
          url: "https://react.dev",
        },
      ],
    },
  ],
  staticProps: {},
};
