import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const fractalBackgroundConfig: ComponentConfig = {
  slug: "fractal-background",
  name: "Fractal Background",
  category: "background",
  tags: ["fractal", "math", "recursive", "pattern", "zoom"],
  componentPath: "app/meta/background/fractal/FractalBackground.tsx",
  showDemoByDefault: true,
  demoVariant: "hero",
  props: [
    {
      name: "colorStart",
      type: "color",
      default: "#050815",
      description: "Background base color of the fractal.",
    },
    {
      name: "colorEnd",
      type: "color",
      default: "#204080",
      description: "Glow/Detail color of the fractal.",
    },
    {
      name: "intensity",
      type: "number",
      default: 1.0,
      min: 0.5,
      max: 2.0,
      step: 0.1,
      description: "Overall brightness multiplier for the WebGL output.",
    },
    {
      name: "speed",
      type: "number",
      default: 0.15,
      min: 0,
      max: 1.0,
      step: 0.01,
      description: "Speed of the fractal's metamorphic animation.",
    },
    {
      name: "zoom",
      type: "number",
      default: 2.8,
      min: 1.0,
      max: 5.0,
      step: 0.1,
      description: "Zoom level into the Julia set coordinates.",
    },
    {
      name: "morphRange",
      type: "number",
      default: 0.1,
      min: 0,
      max: 0.5,
      step: 0.01,
      description: "Amplitude of the complex constant 'c' transformation.",
    },
    {
      name: "enableParallax",
      type: "boolean",
      default: true,
      description: "Enables mouse-tracking parallax shift for a 3D feeling.",
    },
  ],
  presets: [
    {
      id: "deep-sea",
      label: "Deep Sea",
      config: {
        colorStart: "#050815",
        colorEnd: "#204080",
        speed: 0.15,
        zoom: 2.8,
        intensity: 1.0,
        morphRange: 0.1,
        enableParallax: true,
      },
    },
    {
      id: "nebula",
      label: "Cosmic Nebula",
      config: {
        colorStart: "#0A0215",
        colorEnd: "#802060",
        speed: 0.1,
        zoom: 2.5,
        intensity: 1.2,
        morphRange: 0.15,
        enableParallax: true,
      },
    },
    {
      id: "emerald",
      label: "Emerald Light",
      config: {
        colorStart: "#021208",
        colorEnd: "#208040",
        speed: 0.08,
        zoom: 3.2,
        intensity: 0.9,
        morphRange: 0.05,
        enableParallax: false,
      },
    },
    {
      id: "supernova",
      label: "Supernova",
      config: {
        colorStart: "#150802",
        colorEnd: "#CC6633",
        speed: 0.3,
        zoom: 1.8,
        intensity: 1.5,
        morphRange: 0.2,
        enableParallax: true,
      },
    },
    {
      id: "neon-cyber",
      label: "Neon Cyber",
      config: {
        colorStart: "#1A0033",
        colorEnd: "#FF00FF",
        speed: 0.2,
        zoom: 3.5,
        intensity: 1.3,
        morphRange: 0.12,
        enableParallax: true,
      },
    },
    {
      id: "frozen-glace",
      label: "Frozen Glace",
      config: {
        colorStart: "#001A33",
        colorEnd: "#99FFFF",
        speed: 0.05,
        zoom: 4.5,
        intensity: 0.8,
        morphRange: 0.02,
        enableParallax: true,
      },
    },
    {
      id: "blood-moon",
      label: "Blood Moon",
      config: {
        colorStart: "#1A0000",
        colorEnd: "#FF3300",
        speed: 0.25,
        zoom: 2.2,
        intensity: 1.4,
        morphRange: 0.18,
        enableParallax: true,
      },
    },
    {
      id: "golden-artifact",
      label: "Golden Artifact",
      config: {
        colorStart: "#261A00",
        colorEnd: "#FFD700",
        speed: 0.1,
        zoom: 3.0,
        intensity: 1.1,
        morphRange: 0.08,
        enableParallax: true,
      },
    },
    {
      id: "phantom-grey",
      label: "Phantom Grey",
      config: {
        colorStart: "#0D0D0D",
        colorEnd: "#CCCCCC",
        speed: 0.03,
        zoom: 2.8,
        intensity: 0.7,
        morphRange: 0.01,
        enableParallax: false,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
    {
      title: "References",
      items: [
        {
          name: "Julia Set Explorer",
          role: "Fractal Math",
          url: "https://en.wikipedia.org/wiki/Julia_set",
        },
      ],
    },
  ],
};
