import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const kaleidoscopicConfig: ComponentConfig = {
  slug: "kaleidoscopic",
  name: "Kaleidoscopic",
  category: "background",
  tags: ["kaleidoscope", "fractal", "mirror", "symmetry", "pattern"],
  componentPath: "app/meta/background/fractal/Kaleidoscopic.tsx",
  props: [
    {
      name: "iterations",
      type: "number",
      default: 4,
      min: 1,
      max: 7,
      step: 1,
      description: "Number of domain folding iterations (detail level).",
    },
    {
      name: "scale",
      type: "number",
      default: 1.3,
      min: 0.5,
      max: 2.5,
      step: 0.1,
      description: "Scale factor for the space fold.",
    },
    {
      name: "timeMultiplier",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 5.0,
      step: 0.1,
      description: "Speed multiplier for the animation.",
    },
    {
      name: "rotationSpeed",
      type: "number",
      default: 0.05,
      min: -0.2,
      max: 0.2,
      step: 0.01,
      description: "Speed of the overall rotation.",
    },
    {
      name: "glowIntensity",
      type: "number",
      default: 0.012,
      min: 0.001,
      max: 0.05,
      step: 0.001,
      description: "Base intensity of the glow effect.",
    },
    {
      name: "waveFrequency",
      type: "number",
      default: 8.0,
      min: 1.0,
      max: 20.0,
      step: 0.5,
      description: "Frequency of the sine wave modulation.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Neon",
      config: {
        iterations: 4,
        scale: 1.3,
        timeMultiplier: 1.0,
        rotationSpeed: 0.05,
        glowIntensity: 0.012,
        waveFrequency: 8.0,
        colorA: [0.5, 0.5, 0.5],
        colorB: [0.5, 0.5, 0.5],
        colorC: [1.0, 1.0, 1.0],
        colorD: [0.263, 0.416, 0.557],
      },
    },
    {
      id: "cyberpunk",
      label: "Cyberpunk",
      config: {
        iterations: 5,
        scale: 1.5,
        timeMultiplier: 1.5,
        rotationSpeed: -0.1,
        glowIntensity: 0.02,
        waveFrequency: 12.0,
        colorA: [0.8, 0.5, 0.4],
        colorB: [0.2, 0.4, 0.2],
        colorC: [2.0, 1.0, 1.0],
        colorD: [0.0, 0.25, 0.25],
      },
    },
    {
      id: "gold",
      label: "Gold Elegance",
      config: {
        iterations: 3,
        scale: 1.1,
        timeMultiplier: 0.8,
        rotationSpeed: 0.03,
        glowIntensity: 0.008,
        waveFrequency: 5.0,
        colorA: [0.5, 0.5, 0.5],
        colorB: [0.5, 0.5, 0.5],
        colorC: [1.0, 0.7, 0.4],
        colorD: [0.0, 0.15, 0.2],
      },
    },
    {
      id: "void",
      label: "Deep Void",
      config: {
        iterations: 6,
        scale: 2.0,
        timeMultiplier: 0.5,
        rotationSpeed: 0.01,
        glowIntensity: 0.005,
        waveFrequency: 2.0,
        colorA: [0.1, 0.1, 0.1],
        colorB: [1.0, 1.0, 1.0],
        colorC: [0.5, 0.5, 0.5],
        colorD: [0.3, 0.2, 0.8],
      },
    },
  ],
  credits: [
    {
      title: "Inspiration",
      items: [
        {
          name: "Kishimisu",
          role: "Shader Artist",
          url: "https://www.youtube.com/watch?v=f4s1h2YETNY",
        },
      ],
    },
  ],
};
