import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const bubbleGradientConfig: ComponentConfig = {
  slug: "bubble-gradient",
  name: "Bubble Gradient",
  category: "background",
  tags: ["bubble", "gradient", "color", "fluid", "soft"],
  componentPath: "app/meta/background/gradient/BubbleGradient.tsx",
  props: [
    {
      name: "backgroundStart",
      type: "color",
      default: "#050608",
      description: "Starting color for the dark background gradient.",
    },
    {
      name: "backgroundEnd",
      type: "color",
      default: "#171B21",
      description: "Ending color for the dark background gradient.",
    },
    {
      name: "bubbleColors",
      type: "string",
      default: "#F6F7F8, #CDD2D8, #9AA2AD, #5B6470, #262C33",
      description:
        "Five comma-separated bubble colors. Keeps grayscale by default.",
    },
    {
      name: "interactiveColor",
      type: "color",
      default: "#FFFFFF",
      description: "Highlight color for the cursor-following glow bubble.",
    },
    {
      name: "circleSize",
      type: "number",
      default: 78,
      min: 48,
      max: 110,
      step: 2,
      description: "Base bubble size as a percentage of the container.",
    },
    {
      name: "speedMultiplier",
      type: "number",
      default: 1.0,
      min: 0.5,
      max: 1.8,
      step: 0.05,
      description: "Scales the animation speed for all background bubbles.",
    },
    {
      name: "blurStrength",
      type: "number",
      default: 40,
      min: 10,
      max: 80,
      step: 2,
      description:
        "Additional blur applied after the goo filter for a softer cloud effect.",
    },
    {
      name: "gooBlur",
      type: "number",
      default: 10,
      min: 4,
      max: 20,
      step: 1,
      description:
        "Blur amount inside the SVG goo filter before the bubbles merge.",
    },
    {
      name: "gooStrength",
      type: "number",
      default: 18,
      min: 8,
      max: 28,
      step: 1,
      description:
        "Controls how aggressively overlapping bubbles fuse together.",
    },
    {
      name: "gooOffset",
      type: "number",
      default: -8,
      min: -20,
      max: 0,
      step: 1,
      description: "Threshold offset for the goo filter.",
    },
    {
      name: "blendMode",
      type: "select",
      default: "screen",
      options: [
        { id: "screen", label: "Screen" },
        { id: "soft-light", label: "Soft Light" },
        { id: "hard-light", label: "Hard Light" },
        { id: "lighten", label: "Lighten" },
      ],
      description: "Blend mode used for all bubble layers.",
    },
    {
      name: "interactiveRadius",
      type: "number",
      default: 280,
      min: 120,
      max: 420,
      step: 10,
      description: "Radius of the cursor-following highlight bubble in pixels.",
    },
    {
      name: "interactiveFollow",
      type: "number",
      default: 0.12,
      min: 0.02,
      max: 0.3,
      step: 0.01,
      description:
        "Follow smoothing for the interactive bubble. Lower feels floatier.",
    },
    {
      name: "bubbleOpacity",
      type: "number",
      default: 0.84,
      min: 0.3,
      max: 1.0,
      step: 0.05,
      description: "Master opacity multiplier for the animated layers.",
    },
    {
      name: "interactiveOpacity",
      type: "number",
      default: 0.7,
      min: 0.1,
      max: 1.0,
      step: 0.05,
      description: "Opacity of the interactive cursor glow bubble.",
    },
    {
      name: "contrast",
      type: "number",
      default: 118,
      min: 80,
      max: 150,
      step: 2,
      description: "Final contrast applied to the merged bubble stack.",
    },
    {
      name: "brightness",
      type: "number",
      default: 94,
      min: 70,
      max: 120,
      step: 2,
      description: "Final brightness applied to the merged bubble stack.",
    },
    {
      name: "saturation",
      type: "number",
      default: 72,
      min: 0,
      max: 140,
      step: 5,
      description: "Final saturation applied to the merged bubble stack.",
    },
    {
      name: "noiseOpacity",
      type: "number",
      default: 0.08,
      min: 0,
      max: 0.2,
      step: 0.01,
      description: "Opacity of the subtle texture overlay.",
    },
    {
      name: "vignetteOpacity",
      type: "number",
      default: 0.26,
      min: 0,
      max: 0.5,
      step: 0.01,
      description: "Strength of the outer vignette.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Graphite Mist (Default)",
      config: {
        backgroundStart: "#040507",
        backgroundEnd: "#171B21",
        bubbleColors: "#F4F4F5, #D5D9E0, #9FA7B2, #5D6670, #242A31",
        interactiveColor: "#FFFFFF",
        circleSize: 78,
        blurStrength: 42,
        gooBlur: 10,
        gooStrength: 18,
        bubbleOpacity: 0.82,
        interactiveOpacity: 0.72,
        interactiveRadius: 280,
        speedMultiplier: 1,
        blendMode: "screen",
        contrast: 118,
        brightness: 94,
        saturation: 72,
        noiseOpacity: 0.08,
        vignetteOpacity: 0.28,
      },
    },
    {
      id: "smoke",
      label: "Smoked Chrome",
      config: {
        backgroundStart: "#07080B",
        backgroundEnd: "#20242B",
        bubbleColors: "#F7F9FB, #C8D0DB, #8E97A2, #4C545E, #1B1F25",
        interactiveColor: "#DCE6F2",
        circleSize: 84,
        blurStrength: 48,
        gooBlur: 12,
        gooStrength: 20,
        bubbleOpacity: 0.9,
        interactiveOpacity: 0.62,
        interactiveRadius: 320,
        speedMultiplier: 0.85,
        blendMode: "soft-light",
        contrast: 122,
        brightness: 88,
        saturation: 56,
        noiseOpacity: 0.12,
        vignetteOpacity: 0.34,
      },
    },
    {
      id: "ash",
      label: "Ash Bloom",
      config: {
        backgroundStart: "#050608",
        backgroundEnd: "#12161C",
        bubbleColors: "#EDEEF1, #B8C0CB, #767F8B, #434A54, #20242C",
        interactiveColor: "#C9D3DE",
        circleSize: 72,
        blurStrength: 36,
        gooBlur: 9,
        gooStrength: 17,
        bubbleOpacity: 0.78,
        interactiveOpacity: 0.55,
        interactiveRadius: 250,
        speedMultiplier: 1.15,
        blendMode: "lighten",
        contrast: 112,
        brightness: 98,
        saturation: 64,
        noiseOpacity: 0.06,
        vignetteOpacity: 0.22,
      },
    },
  ],
  credits: [
    {
      title: "Visual Direction",
      items: [
        {
          name: "Gooey Bubble Gradient",
          role: "Reference Style",
          url: "https://css-tricks.com/gooey-effect/",
        },
      ],
    },
    {
      title: "Project",
      items: [
        {
          name: "React Bytes",
          role: "Component Collection",
          url: "https://reactbytes.dev",
        },
      ],
    },
  ],
};
