import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const helonBraidConfig: ComponentConfig = {
  slug: "helon-braid",
  name: "Helon Braid",
  category: "background",
  tags: ["braid", "wave", "rope", "weave", "ribbon"],
  componentPath: "app/meta/background/wave/HelonBraid/HelonBraid.tsx",
  description: "An interactive hex-grid braid wave background canvas component with customizable wave dynamics and blueprint styling.",
  npmPackageName: "@reactbytes/helon-braid",
  version: "1.0.0",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
    "react-dom": "^18.0.0",
  },
  showDemoByDefault: true,
  demoVariant: "text",
  props: [
    {
      name: "spacingX",
      type: "number",
      default: 80,
      min: 30,
      max: 200,
      step: 1,
      description: "Horizontal node spacing (which defines cell columns).",
    },
    {
      name: "baseRadius",
      type: "number",
      default: 65,
      min: 20,
      max: 200,
      step: 1,
      description: "Structural blueprint arc radius and spacing factor.",
    },
    {
      name: "speed",
      type: "number",
      default: 0.05,
      min: 0.01,
      max: 0.2,
      step: 0.01,
      description: "Base speed coefficient for wave animations.",
    },
    {
      name: "excitationMultiplier",
      type: "number",
      default: 12,
      min: 1,
      max: 30,
      step: 1,
      description: "Intensity multiplier of node-trigger excitations.",
    },
    {
      name: "backgroundColor",
      type: "color",
      default: "#070a12",
      description:
        "Background container color (also used for masking Over/Under weaving layers).",
    },
    {
      name: "blueprintColor1",
      type: "color",
      default: "#ffffff",
      description: "Color of structural blueprint layer 1 (outer circles).",
    },
    {
      name: "blueprintColor2",
      type: "color",
      default: "#3b82f6",
      description: "Color of structural blueprint layer 2 (under strands & mid circles).",
    },
    {
      name: "blueprintColor3",
      type: "color",
      default: "#ec4899",
      description: "Color of structural blueprint layer 3 (over strands & inner circles).",
    },
    {
      name: "blueprintOpacity",
      type: "number",
      default: 0.02,
      min: 0,
      max: 1,
      step: 0.01,
      description: "Opacity of the structural background blueprint lines.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Preon",
      config: {
        spacingX: 80,
        baseRadius: 65,
        speed: 0.05,
        excitationMultiplier: 12,
        backgroundColor: "#070a12",
        blueprintColor1: "#ffffff",
        blueprintColor2: "#00d4ff",
        blueprintColor3: "#3b82f6",
        blueprintOpacity: 0.02,
      },
    },
    {
      id: "cosmic",
      label: "Cosmic Braid",
      config: {
        spacingX: 120,
        baseRadius: 100,
        speed: 0.02,
        excitationMultiplier: 18,
        backgroundColor: "#080315",
        blueprintColor1: "#ffffff",
        blueprintColor2: "#a600ff",
        blueprintColor3: "#ec4899",
        blueprintOpacity: 0.04,
      },
    },
    {
      id: "hyper",
      label: "Quantum Flare",
      config: {
        spacingX: 50,
        baseRadius: 40,
        speed: 0.12,
        excitationMultiplier: 25,
        backgroundColor: "#11020a",
        blueprintColor1: "#ffffff",
        blueprintColor2: "#ff0055",
        blueprintColor3: "#ffaa00",
        blueprintOpacity: 0.05,
      },
    },
    {
      id: "emerald",
      label: "Bio Synapse",
      config: {
        spacingX: 95,
        baseRadius: 75,
        speed: 0.04,
        excitationMultiplier: 10,
        backgroundColor: "#020f08",
        blueprintColor1: "#ffffff",
        blueprintColor2: "#00ff55",
        blueprintColor3: "#00aaff",
        blueprintOpacity: 0.03,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
  ],
};
