import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const warpSpeedConfig: ComponentConfig = {
  slug: "warp-speed",
  name: "Warp Speed",
  category: "background",
  componentPath: "app/meta/background/space/WarpSpeed/WarpSpeed.tsx",
  showDemoByDefault: true,
  demoVariant: "hero",
  props: [
    {
      name: "starCount",
      type: "number",
      default: 400,
      min: 50,
      max: 1500,
      step: 50,
      description: "The total number of stars in the field.",
    },
    {
      name: "sensitivity",
      type: "number",
      default: 0.8,
      min: 0.1,
      max: 3.0,
      step: 0.1,
      description: "Scroll velocity multiplier.",
    },
    {
      name: "friction",
      type: "number",
      default: 0.95,
      min: 0.80,
      max: 0.99,
      step: 0.01,
      description: "Inertia decay factor. Lower values slow down the ship faster.",
    },
    {
      name: "hueShift",
      type: "number",
      default: 216,
      min: 0,
      max: 360,
      step: 1,
      description: "HSL base color hue (0-360 range) for star trails and ship color.",
    },
    {
      name: "trailLength",
      type: "number",
      default: 1.0,
      min: 0.2,
      max: 3.0,
      step: 0.1,
      description: "Length of the motion blur trailing effect. Higher is longer trails.",
    },
    {
      name: "minSize",
      type: "number",
      default: 0.5,
      min: 0.1,
      max: 3.0,
      step: 0.1,
      description: "Minimum size of a star in pixels.",
    },
    {
      name: "maxSize",
      type: "number",
      default: 3.0,
      min: 1.0,
      max: 10.0,
      step: 0.1,
      description: "Maximum size of a star in pixels.",
    },
    {
      name: "showShip",
      type: "boolean",
      default: true,
      description: "Whether to render the centered spaceship.",
    },
    {
      name: "showMouseHint",
      type: "boolean",
      default: true,
      description: "Whether to overlay a pulsing 'Scroll to Fly' hint.",
    },
    {
      name: "preventPageScroll",
      type: "boolean",
      default: false,
      description: "If true, wheel actions will call preventDefault on parent containers (useful for fullscreen mode).",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Classic Warp",
      config: {
        starCount: 400,
        sensitivity: 0.8,
        friction: 0.95,
        hueShift: 216,
        trailLength: 1.0,
        minSize: 0.5,
        maxSize: 3.0,
        showShip: true,
        showMouseHint: true,
        preventPageScroll: false,
      },
    },
    {
      id: "hyperdrive",
      label: "Hyperdrive",
      config: {
        starCount: 1000,
        sensitivity: 2.0,
        friction: 0.98,
        hueShift: 120,
        trailLength: 0.5,
        minSize: 0.8,
        maxSize: 4.5,
        showShip: true,
        showMouseHint: false,
        preventPageScroll: false,
      },
    },
    {
      id: "solar",
      label: "Solar Nebula",
      config: {
        starCount: 600,
        sensitivity: 0.4,
        friction: 0.90,
        hueShift: 25,
        trailLength: 2.0,
        minSize: 0.3,
        maxSize: 2.5,
        showShip: true,
        showMouseHint: true,
        preventPageScroll: false,
      },
    },
    {
      id: "deepspace",
      label: "Deep Space",
      config: {
        starCount: 300,
        sensitivity: 1.2,
        friction: 0.85,
        hueShift: 0,
        trailLength: 1.0,
        minSize: 0.2,
        maxSize: 1.5,
        showShip: false,
        showMouseHint: false,
        preventPageScroll: false,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "WarpSpeed Starfield",
          role: "Creative Developer",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Library",
          url: "https://react.dev",
        },
        {
          name: "Lucide React",
          role: "Icons",
          url: "https://lucide.dev",
        },
      ],
    },
  ],
};
