import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const concentricWavesConfig: ComponentConfig = {
  slug: "concentric-waves",
  name: "Concentric Waves",
  category: "background",
  tags: ["concentric", "waves", "ripple", "rings", "pulse"],
  componentPath: "app/meta/background/wave/ConcentricWaves/ConcentricWaves.tsx",
  showDemoByDefault: true,
  demoVariant: "text",

  // Automated NPM Publishing Metadata
  npmPackageName: "@reactbytes/concentric-waves",
  version: "1.0.0",
  description: "A highly performant, responsive canvas background engine rendering rotating gradient waves that adapt dynamically to parent boundaries without center shifting.",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
  },

  props: [
    {
      name: "layerCount",
      type: "number",
      default: 16,
      min: 4,
      max: 30,
      step: 1,
      description: "Number of concentric ring layers.",
    },
    {
      name: "ringSpacing",
      type: "number",
      default: 45,
      min: 10,
      max: 100,
      step: 1,
      description: "Distance between each main ring.",
    },
    {
      name: "baseRadiusStart",
      type: "number",
      default: 40,
      min: 10,
      max: 100,
      step: 1,
      description: "Starting radius of the innermost ring.",
    },
    {
      name: "pulseSpeedMultiplier",
      type: "number",
      default: 1.0,
      min: 0.1,
      max: 5.0,
      step: 0.1,
      description: "Multiplier for how fast the rings pulse.",
    },
    {
      name: "spinDurationMs",
      type: "number",
      default: 2500,
      min: 500,
      max: 10000,
      step: 100,
      description: "How long it takes for the gradient to complete a 360 rotation (in ms).",
    },
    {
      name: "minOpacity",
      type: "number",
      default: 0.4,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Minimum opacity for the main rings during their pulse.",
    },
    {
      name: "maxOpacity",
      type: "number",
      default: 0.9,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Maximum opacity for the main rings during their pulse.",
    },
    {
      name: "minThickness",
      type: "number",
      default: 4,
      min: 1,
      max: 10,
      step: 1,
      description: "Thickness of the innermost main ring.",
    },
    {
      name: "maxThickness",
      type: "number",
      default: 16,
      min: 1,
      max: 30,
      step: 1,
      description: "Thickness of the outermost main ring.",
    },
    {
      name: "mainColor1",
      type: "color",
      default: "#5ddcff",
      description: "Start color for the main thick rings gradient.",
    },
    {
      name: "mainColor2",
      type: "color",
      default: "#3c67e3",
      description: "Middle color for the main thick rings gradient.",
    },
    {
      name: "mainColor3",
      type: "color",
      default: "#4e00c2",
      description: "End color for the main thick rings gradient.",
    },
    {
      name: "midColor1",
      type: "color",
      default: "#f3f4f6",
      description: "Start color for the intermediate thin rings gradient.",
    },
    {
      name: "midColor2",
      type: "color",
      default: "#9ca3af",
      description: "Middle color for the intermediate thin rings gradient.",
    },
    {
      name: "midColor3",
      type: "color",
      default: "#374151",
      description: "End color for the intermediate thin rings gradient.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#05080f",
      description: "Background color of the canvas.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Cyan-Purple",
      config: {
        layerCount: 16,
        ringSpacing: 45,
        baseRadiusStart: 40,
        pulseSpeedMultiplier: 1.0,
        spinDurationMs: 2500,
        minOpacity: 0.4,
        maxOpacity: 0.9,
        minThickness: 4,
        maxThickness: 16,
        mainColor1: "#5ddcff",
        mainColor2: "#3c67e3",
        mainColor3: "#4e00c2",
        midColor1: "#f3f4f6",
        midColor2: "#9ca3af",
        midColor3: "#374151",
        bgColor: "#05080f",
      },
    },
    {
      id: "sunset",
      label: "Sunset Glow",
      config: {
        layerCount: 12,
        ringSpacing: 50,
        baseRadiusStart: 30,
        pulseSpeedMultiplier: 0.8,
        spinDurationMs: 4000,
        minOpacity: 0.5,
        maxOpacity: 1.0,
        minThickness: 2,
        maxThickness: 20,
        mainColor1: "#ff7b00",
        mainColor2: "#ff0055",
        mainColor3: "#7a00ff",
        midColor1: "#ffe4b5",
        midColor2: "#ff8c00",
        midColor3: "#8b0000",
        bgColor: "#0a0005",
      },
    },
    {
      id: "matrix",
      label: "Digital Matrix",
      config: {
        layerCount: 20,
        ringSpacing: 30,
        baseRadiusStart: 20,
        pulseSpeedMultiplier: 1.5,
        spinDurationMs: 1500,
        minOpacity: 0.2,
        maxOpacity: 0.8,
        minThickness: 1,
        maxThickness: 8,
        mainColor1: "#00ff41",
        mainColor2: "#008f11",
        mainColor3: "#003b00",
        midColor1: "#aaffaa",
        midColor2: "#00ff41",
        midColor3: "#008f11",
        bgColor: "#000500",
      },
    },
    {
      id: "minimalist",
      label: "Minimalist Grayscale",
      config: {
        layerCount: 10,
        ringSpacing: 60,
        baseRadiusStart: 50,
        pulseSpeedMultiplier: 0.5,
        spinDurationMs: 6000,
        minOpacity: 0.1,
        maxOpacity: 0.5,
        minThickness: 1,
        maxThickness: 5,
        mainColor1: "#ffffff",
        mainColor2: "#888888",
        mainColor3: "#222222",
        midColor1: "#eeeeee",
        midColor2: "#aaaaaa",
        midColor3: "#444444",
        bgColor: "#000000",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
  ],
};