import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const concentricWavesConfig: ComponentConfig = {
  slug: "concentric-waves",
  name: "Concentric Waves",
  category: "background",
  tags: ["concentric", "waves", "ripple", "rings", "pulse"],
  componentPath: "app/meta/background/wave/ConcentricWaves/ConcentricWaves.tsx",
  props: [
    {
      name: "layerCount",
      type: "number",
      default: 16,
      min: 4,
      max: 30,
      step: 1,
      description: "Number of concentric ring layers.",
    },
    {
      name: "ringSpacing",
      type: "number",
      default: 45,
      min: 10,
      max: 100,
      step: 1,
      description: "Distance between each main ring.",
    },
    {
      name: "baseRadiusStart",
      type: "number",
      default: 40,
      min: 10,
      max: 100,
      step: 1,
      description: "Starting radius of the innermost ring.",
    },
    {
      name: "pulseSpeedMultiplier",
      type: "number",
      default: 1.0,
      min: 0.1,
      max: 5.0,
      step: 0.1,
      description: "Multiplier for how fast the rings pulse.",
    },
    {
      name: "spinDurationMs",
      type: "number",
      default: 2500,
      min: 500,
      max: 10000,
      step: 100,
      description:
        "How long it takes for the gradient to complete a 360 rotation (in ms).",
    },
    {
      name: "minOpacity",
      type: "number",
      default: 0.4,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Minimum opacity for the main rings during their pulse.",
    },
    {
      name: "maxOpacity",
      type: "number",
      default: 0.9,
      min: 0.0,
      max: 1.0,
      step: 0.1,
      description: "Maximum opacity for the main rings during their pulse.",
    },
    {
      name: "minThickness",
      type: "number",
      default: 4,
      min: 1,
      max: 10,
      step: 1,
      description: "Thickness of the innermost main ring.",
    },
    {
      name: "maxThickness",
      type: "number",
      default: 16,
      min: 1,
      max: 30,
      step: 1,
      description: "Thickness of the outermost main ring.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#05080f",
      description: "Background color of the canvas.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Cyan-Purple",
      config: {
        layerCount: 16,
        ringSpacing: 45,
        baseRadiusStart: 40,
        pulseSpeedMultiplier: 1.0,
        spinDurationMs: 2500,
        minOpacity: 0.4,
        maxOpacity: 0.9,
        minThickness: 4,
        maxThickness: 16,
        mainGradientColors: ["#5ddcff", "#3c67e3", "#4e00c2"],
        midGradientColors: ["#f3f4f6", "#9ca3af", "#374151"],
        bgColor: "#05080f",
      },
    },
    {
      id: "sunset",
      label: "Sunset Glow",
      config: {
        layerCount: 12,
        ringSpacing: 50,
        baseRadiusStart: 30,
        pulseSpeedMultiplier: 0.8,
        spinDurationMs: 4000,
        minOpacity: 0.5,
        maxOpacity: 1.0,
        minThickness: 2,
        maxThickness: 20,
        mainGradientColors: ["#ff7b00", "#ff0055", "#7a00ff"],
        midGradientColors: ["#ffe4b5", "#ff8c00", "#8b0000"],
        bgColor: "#0a0005",
      },
    },
    {
      id: "matrix",
      label: "Digital Matrix",
      config: {
        layerCount: 20,
        ringSpacing: 30,
        baseRadiusStart: 20,
        pulseSpeedMultiplier: 1.5,
        spinDurationMs: 1500,
        minOpacity: 0.2,
        maxOpacity: 0.8,
        minThickness: 1,
        maxThickness: 8,
        mainGradientColors: ["#00ff41", "#008f11", "#003b00"],
        midGradientColors: ["#aaffaa", "#00ff41", "#008f11"],
        bgColor: "#000500",
      },
    },
    {
      id: "minimalist",
      label: "Minimalist Grayscale",
      config: {
        layerCount: 10,
        ringSpacing: 60,
        baseRadiusStart: 50,
        pulseSpeedMultiplier: 0.5,
        spinDurationMs: 6000,
        minOpacity: 0.1,
        maxOpacity: 0.5,
        minThickness: 1,
        maxThickness: 5,
        mainGradientColors: ["#ffffff", "#888888", "#222222"],
        midGradientColors: ["#eeeeee", "#aaaaaa", "#444444"],
        bgColor: "#000000",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ReactBytes",
          role: "Library",
          url: "#",
        },
      ],
    },
  ],
};
