import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const tectonicLatticeTextConfig: ComponentConfig = {
  slug: "tectonic-lattice-text",
  name: "Tectonic Lattice",
  category: "text",
  tags: ["tectonic", "lattice", "grid", "fracture", "shift"],
  componentPath: "app/meta/text/TectonicLatticeText/TectonicLatticeText.tsx",
  props: [
    {
      name: "text",
      type: "string",
      default: "STRUCT",
      description: "The typography word to render as a grid lattice.",
    },
    {
      name: "railMode",
      type: "select",
      default: "diagonal",
      options: [
        { id: "diagonal", label: "Diagonal" },
        { id: "orthogonal", label: "Orthogonal" },
        { id: "axial-x", label: "Axial X" },
        { id: "axial-y", label: "Axial Y" },
        { id: "shattered", label: "Shattered" },
      ],
      description: "The rail layout defining displacement constraints.",
    },
    {
      name: "blockSize",
      type: "number",
      default: 8,
      min: 4,
      max: 16,
      step: 1,
      description: "Size in pixels of each block in the lattice.",
    },
    {
      name: "blockPadding",
      type: "number",
      default: 1.5,
      min: 0,
      max: 5,
      step: 0.5,
      description: "Padding space between blocks.",
    },
    {
      name: "influenceRadius",
      type: "number",
      default: 100,
      min: 40,
      max: 200,
      step: 5,
      description: "Cursor proximity radius for block interaction.",
    },
    {
      name: "pushStrength",
      type: "number",
      default: 9.0,
      min: 2,
      max: 20,
      step: 0.5,
      description: "Force multiplier pushing blocks away from the cursor.",
    },
    {
      name: "blockMass",
      type: "number",
      default: 1.0,
      min: 0.2,
      max: 4.0,
      step: 0.1,
      description: "Simulated mass slowing down or speeding up spring physics.",
    },
    {
      name: "snapStiffness",
      type: "number",
      default: 0.08,
      min: 0.01,
      max: 0.3,
      step: 0.01,
      description: "Stiffness of the snap-back home-seeking spring.",
    },
    {
      name: "friction",
      type: "number",
      default: 0.82,
      min: 0.5,
      max: 0.99,
      step: 0.01,
      description: "Kinetic friction multiplier slowing block motion.",
    },
    {
      name: "maxOffset",
      type: "number",
      default: 160,
      min: 40,
      max: 300,
      step: 10,
      description: "Maximum offset limit blocks can slide.",
    },
    {
      name: "skewIntensity",
      type: "number",
      default: 0.15,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      description: "Visual shear/skew strength applied under motion stress.",
    },
    {
      name: "baseColor",
      type: "color",
      default: "#ffffff",
      description: "Resting foreground color of lattice blocks.",
    },
    {
      name: "stressedBlockColor",
      type: "color",
      default: "#c084fc",
      description: "Color of blocks when pushed/stressed by the cursor.",
    },
    {
      name: "wireframeColor",
      type: "color",
      default: "rgba(168, 85, 247, 0.45)",
      description: "Underlying rail lattice wireframe background color.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#070709",
      description: "Lattice canvas scene background color.",
    },
  ],
  presets: [
    {
      id: "matrix",
      label: "Ametrine (Default)",
      config: {
        text: "STRUCT",
        railMode: "diagonal",
        blockSize: 8,
        blockPadding: 1.5,
        influenceRadius: 100,
        pushStrength: 9.0,
        blockMass: 1.0,
        snapStiffness: 0.08,
        friction: 0.82,
        maxOffset: 160,
        skewIntensity: 0.15,
        baseColor: "#ffffff",
        wireframeColor: "rgba(168, 85, 247, 0.45)",
        stressedBlockColor: "#c084fc",
        bgColor: "#070709",
      },
    },
    {
      id: "cyber",
      label: "Cyberpunk",
      config: {
        text: "FRACTURE",
        railMode: "diagonal",
        blockSize: 8,
        blockPadding: 1.5,
        influenceRadius: 100,
        pushStrength: 9.0,
        blockMass: 1.0,
        snapStiffness: 0.08,
        friction: 0.82,
        maxOffset: 160,
        skewIntensity: 0.15,
        baseColor: "#00f5ff",
        wireframeColor: "rgba(255, 0, 110, 0.35)",
        stressedBlockColor: "#ff006e",
        bgColor: "#050508",
      },
    },
    {
      id: "mono",
      label: "Industrial",
      config: {
        text: "MATRIX",
        railMode: "orthogonal",
        blockSize: 8,
        blockPadding: 1.5,
        influenceRadius: 100,
        pushStrength: 9.0,
        blockMass: 1.0,
        snapStiffness: 0.08,
        friction: 0.82,
        maxOffset: 160,
        skewIntensity: 0.15,
        baseColor: "#f3f4f6",
        wireframeColor: "rgba(156, 163, 175, 0.4)",
        stressedBlockColor: "#374151",
        bgColor: "#111827",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "React Bytes",
          role: "Author",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Framework",
          url: "https://react.dev",
        },
      ],
    },
  ],
  staticProps: {},
};
