import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const atmosphericDriftConfig: ComponentConfig = {
  slug: "atmospheric-drift",
  name: "Atmospheric Drift",
  category: "background",
  tags: ["drift", "particles", "atmosphere", "floating", "ambient"],
  componentPath: "app/meta/background/AtmosphericDrift/AtmosphericDrift.tsx",
  showDemoByDefault: true,
  demoVariant: "hero",
  npmPackageName: "@reactbytes/atmospheric-drift",
  version: "1.0.0",
  description: "An interactive, physics-based canvas component featuring an atmospheric drift animation.",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
    "react-dom": "^18.0.0"
  },
  props: [
    {
      name: "preset",
      type: "select",
      default: "mistral",
      options: [
        { id: "mistral", label: "Mistral Surge" },
        { id: "sirocco", label: "Sirocco Dust" },
        { id: "aurora", label: "Boreal Flow" },
        { id: "storm", label: "Winter Gale" },
        { id: "zen", label: "Zenith Drift" },
      ],
      description: "Active wind preset determining flow configurations.",
    },
    {
      name: "palette",
      type: "select",
      default: "midnight",
      options: [
        { id: "midnight", label: "Midnight Blue" },
        { id: "aurora", label: "Aurora Green" },
        { id: "sirocco", label: "Sirocco Gold" },
        { id: "volcanic", label: "Volcanic Red" },
        { id: "monochrome", label: "Monochrome" },
      ],
      description: "Active color spectrum mapping for the particles velocity.",
    },
    {
      name: "showGrid",
      type: "boolean",
      default: true,
      description: "Renders a background mathematical alignment grid overlay.",
    },
    {
      name: "audioEnabled",
      type: "boolean",
      default: false,
      description:
        "Triggers pink noise ambient wind sound synthesis mapped to flow speed.",
    },
    {
      name: "particleCount",
      type: "number",
      default: 15000,
      min: 4000,
      max: 25000,
      step: 1000,
      description: "Total count of WebGL animated wind vector particles.",
    },
    {
      name: "flowSpeed",
      type: "number",
      default: 3.1,
      min: 0.5,
      max: 5.0,
      step: 0.1,
      description: "Multiplier controlling velocity and drift speed.",
    },
    {
      name: "trailPersistence",
      type: "number",
      default: 0.94,
      min: 0.8,
      max: 0.99,
      step: 0.01,
      description: "Retention rate of line drawing trails on FBO texture.",
    },
    {
      name: "windWobble",
      type: "number",
      default: 0.024,
      min: 0.0,
      max: 0.08,
      step: 0.002,
      description: "Frictional cell vibration/noise amplitude.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Mistral Surge (Default)",
      config: {
        preset: "mistral",
        palette: "midnight",
        showGrid: true,
        audioEnabled: false,
        particleCount: 15000,
        flowSpeed: 3.1,
        trailPersistence: 0.94,
        windWobble: 0.024,
      },
    },
    {
      id: "sirocco",
      label: "Sirocco Dust",
      config: {
        preset: "sirocco",
        palette: "sirocco",
        showGrid: true,
        audioEnabled: false,
        particleCount: 12000,
        flowSpeed: 2.4,
        trailPersistence: 0.92,
        windWobble: 0.022,
      },
    },
    {
      id: "aurora",
      label: "Boreal Flow",
      config: {
        preset: "aurora",
        palette: "aurora",
        showGrid: true,
        audioEnabled: false,
        particleCount: 18000,
        flowSpeed: 1.8,
        trailPersistence: 0.96,
        windWobble: 0.012,
      },
    },
    {
      id: "storm",
      label: "Winter Gale",
      config: {
        preset: "storm",
        palette: "volcanic",
        showGrid: true,
        audioEnabled: true,
        particleCount: 22000,
        flowSpeed: 3.8,
        trailPersistence: 0.88,
        windWobble: 0.035,
      },
    },
    {
      id: "zen",
      label: "Zenith Drift",
      config: {
        preset: "zen",
        palette: "monochrome",
        showGrid: false,
        audioEnabled: false,
        particleCount: 8000,
        flowSpeed: 1.2,
        trailPersistence: 0.97,
        windWobble: 0.005,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
    {
      title: "Physics & Web Audio",
      items: [
        {
          name: "WebGL 2D Flow",
          role: "FBO Vector Simulation",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API",
        },
        {
          name: "Web Audio API",
          role: "Pink Noise Synthesizer",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API",
        },
      ],
    },
  ],
};
