import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const pillTabbedSectionConfig: ComponentConfig = {
  slug: "pill-tabbed-section",
  name: "Pill Tabbed Section",
  category: "miscellaneous",
  tags: ["tabs", "pill", "navigation", "sections", "toggle"],
  componentPath: "app/meta/tabbed/PillTabbedSection/PillTabbedSection.tsx",
  npmPackageName: "@reactbytes/pill-tabbed-section",
  version: "1.0.0",
  dependencies: {
    "framer-motion": "^12.38.0",
    "lucide-react": "^1.7.0",
  },
  peerDependencies: {
    react: "^19.0.0",
    "react-dom": "^19.0.0",
  },
  containerClassName:
    "w-full min-h-[500px] !h-auto flex items-center justify-center p-8 bg-black rounded-[32px] border border-white/5 relative overflow-hidden",
  props: [
    {
      name: "defaultTab",
      type: "select",
      default: "orchestrations",
      options: [
        { id: "home", label: "Dashboard Home" },
        { id: "flow", label: "Data Flow" },
        { id: "modules", label: "Core Modules" },
        { id: "architecture", label: "System Architecture" },
        { id: "orchestrations", label: "Open Orchestrations" },
      ],
      description: "The ID of the tab that should be active on initial render.",
    },
    {
      name: "animationType",
      type: "select",
      default: "kinetic",
      options: [
        { id: "kinetic", label: "Kinetic Pop" },
        { id: "smooth", label: "Smooth Slide" },
        { id: "bounce", label: "Spring Bounce" },
        { id: "fade", label: "Crossfade" },
      ],
      description: "Transition animation style when changing tabs.",
    },
    {
      name: "tabShape",
      type: "select",
      default: "pill",
      options: [
        { id: "pill", label: "Pill Shape" },
        { id: "rounded", label: "Rounded Edges" },
        { id: "square", label: "Sharp Square" },
      ],
      description: "Border radius style of the tabs and components.",
    },
    {
      name: "activeColor",
      type: "color",
      default: "#9b8bf4",
      description: "Active tab icon, text, and active highlight color.",
    },
    {
      name: "inactiveColor",
      type: "color",
      default: "#6b6680",
      description: "Inactive tab icon and text color.",
    },
    {
      name: "glowColor1",
      type: "color",
      default: "#0088ff",
      description: "First color of the glowing border ray gradient.",
    },
    {
      name: "glowColor2",
      type: "color",
      default: "#ff0033",
      description: "Second color of the glowing border ray gradient.",
    },
    {
      name: "glowSpeed",
      type: "number",
      default: 4,
      min: 1,
      max: 10,
      step: 0.5,
      description: "Speed in seconds of the glowing border ray sweep.",
    },
    {
      name: "autoRotate",
      type: "boolean",
      default: false,
      description: "Automatically cycle through tabs.",
    },
    {
      name: "autoRotateInterval",
      type: "number",
      default: 5000,
      min: 1000,
      max: 15000,
      step: 500,
      description: "Time in milliseconds between auto-rotations.",
    },
    {
      name: "pauseOnHover",
      type: "boolean",
      default: true,
      description: "Pause auto-rotation when hover.",
    },
    {
      name: "showNoise",
      type: "boolean",
      default: true,
      description: "Show a shimmering noise overlay in the header.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Classic Neon (Default)",
      config: {
        defaultTab: "orchestrations",
        animationType: "kinetic",
        tabShape: "pill",
        activeColor: "#9b8bf4",
        inactiveColor: "#6b6680",
        glowColor1: "#0088ff",
        glowColor2: "#ff0033",
        glowSpeed: 4,
        autoRotate: false,
        autoRotateInterval: 5000,
        pauseOnHover: true,
        showNoise: true,
      },
    },
    {
      id: "cyberpunk",
      label: "Cyberpunk Pulse",
      config: {
        defaultTab: "orchestrations",
        animationType: "bounce",
        tabShape: "square",
        activeColor: "#fbfb04",
        inactiveColor: "#5f5f7f",
        glowColor1: "#ff00ff",
        glowColor2: "#00ffff",
        glowSpeed: 2,
        autoRotate: true,
        autoRotateInterval: 4000,
        pauseOnHover: true,
        showNoise: true,
      },
    },
    {
      id: "zen-minimalist",
      label: "Zen Minimalist",
      config: {
        defaultTab: "orchestrations",
        animationType: "fade",
        tabShape: "rounded",
        activeColor: "#e4e4e7",
        inactiveColor: "#52525b",
        glowColor1: "#27272a",
        glowColor2: "#3f3f46",
        glowSpeed: 8,
        autoRotate: false,
        autoRotateInterval: 6000,
        pauseOnHover: true,
        showNoise: false,
      },
    },
    {
      id: "ocean-breeze",
      label: "Ocean Breeze",
      config: {
        defaultTab: "orchestrations",
        animationType: "smooth",
        tabShape: "rounded",
        activeColor: "#38bdf8",
        inactiveColor: "#475569",
        glowColor1: "#0ea5e9",
        glowColor2: "#10b981",
        glowSpeed: 5,
        autoRotate: true,
        autoRotateInterval: 3000,
        pauseOnHover: true,
        showNoise: true,
      },
    },
    {
      id: "magma-flow",
      label: "Magma Flow",
      config: {
        defaultTab: "orchestrations",
        animationType: "kinetic",
        tabShape: "pill",
        activeColor: "#f97316",
        inactiveColor: "#78716c",
        glowColor1: "#dc2626",
        glowColor2: "#ea580c",
        glowSpeed: 3,
        autoRotate: false,
        autoRotateInterval: 5000,
        pauseOnHover: true,
        showNoise: true,
      },
    },
  ],
  credits: [
    {
      title: "Libraries",
      items: [
        {
          name: "Framer Motion",
          role: "Animations",
          url: "https://www.framer.com/motion/",
        },
        {
          name: "Lucide React",
          role: "Icons",
          url: "https://lucide.dev",
        },
      ],
    },
    {
      title: "Project Author",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Creator & Lead Designer",
          url: "https://github.com/ChandruMIT-o",
        },
      ],
    },
  ],
};
