import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const fbmNoiseConfig: ComponentConfig = {
  slug: "fbm-noise",
  name: "FBM Vector Shader",
  category: "background",
  tags: ["fbm", "fractal", "noise", "terrain", "organic"],
  componentPath: "app/meta/background/liquid/FbmNoise.tsx",
  showDemoByDefault: true,
  demoVariant: "card",
  props: [
    {
      name: "complex",
      type: "boolean",
      default: false,
      description:
        "Enables layered multi-octave FBM noise calculations for detailed fluid details.",
    },
    {
      name: "paused",
      type: "boolean",
      default: false,
      description: "Halts vector flow movement simulation.",
    },
    {
      name: "scale",
      type: "number",
      default: 3.0,
      min: 0.5,
      max: 10.0,
      step: 0.1,
      description: "Pattern scale zoom multiplier for the noise landscapes.",
    },
    {
      name: "speed",
      type: "number",
      default: 0.1,
      min: 0.0,
      max: 0.4,
      step: 0.005,
      description: "Rate of time flow progression in vector movements.",
    },
    {
      name: "mouseInfluence",
      type: "number",
      default: 0.5,
      min: 0.0,
      max: 3.0,
      step: 0.05,
      description:
        "Pointer warp impact strength scaling dynamic coordinate offsets.",
    },
    {
      name: "brightness",
      type: "number",
      default: 1.0,
      min: 0.1,
      max: 2.5,
      step: 0.05,
      description: "Global brightness intensity multiplier.",
    },
    {
      name: "seed",
      type: "number",
      default: 43758.5453123,
      min: 1000,
      max: 100000,
      step: 1,
      description:
        "Seed coordinate offset for the random generator algorithms.",
    },
    {
      name: "colorR",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 3.0,
      step: 0.05,
      description: "Red color channel bias factor.",
    },
    {
      name: "colorG",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 3.0,
      step: 0.05,
      description: "Green color channel bias factor.",
    },
    {
      name: "colorB",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 3.0,
      step: 0.05,
      description: "Blue color channel bias factor.",
    },
  ],
  presets: [
    {
      id: "nebula",
      label: "Cosmic Aurora",
      config: {
        complex: false,
        scale: 3.5,
        speed: 0.08,
        mouseInfluence: 0.6,
        brightness: 1.0,
        seed: 43758.545,
        colorR: 0.8,
        colorG: 1.2,
        colorB: 1.5,
        paused: false,
      },
    },
    {
      id: "fire",
      label: "Solar Tempest",
      config: {
        complex: true,
        scale: 4.8,
        speed: 0.16,
        mouseInfluence: 1.1,
        brightness: 1.3,
        seed: 1294.551,
        colorR: 2.2,
        colorG: 0.45,
        colorB: 0.1,
        paused: false,
      },
    },
    {
      id: "void",
      label: "Ethereal Abyss",
      config: {
        complex: false,
        scale: 1.8,
        speed: 0.04,
        mouseInfluence: 0.3,
        brightness: 0.85,
        seed: 98765.432,
        colorR: 0.4,
        colorG: 0.7,
        colorB: 1.4,
        paused: false,
      },
    },
    {
      id: "matrix",
      label: "Toxic Quasar",
      config: {
        complex: true,
        scale: 5.0,
        speed: 0.18,
        mouseInfluence: 1.3,
        brightness: 1.15,
        seed: 77777.777,
        colorR: 0.25,
        colorG: 1.8,
        colorB: 0.35,
        paused: false,
      },
    },
    {
      id: "neon",
      label: "Cybernetic Silk",
      config: {
        complex: true,
        scale: 2.8,
        speed: 0.06,
        mouseInfluence: 0.8,
        brightness: 1.2,
        seed: 33333.333,
        colorR: 1.6,
        colorG: 0.25,
        colorB: 1.8,
        paused: false,
      },
    },
  ],
  credits: [
    {
      title: "Shader Conception",
      items: [
        {
          name: "Inigo Quilez",
          role: "Noise Algorithms Creator",
          url: "https://iquilezles.org/",
        },
        {
          name: "Three.js Contributors",
          role: "WebGL Abstraction Framework",
          url: "https://threejs.org/",
        },
      ],
    },
  ],
};
