import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const liquidGridConfig: ComponentConfig = {
  slug: "liquid-grid",
  name: "Liquid Grid",
  category: "background",
  componentPath: "app/meta/background/liquid/LiquidGrid.tsx",
  props: [
    {
      name: "cols",
      type: "number",
      default: 9,
      min: 3,
      max: 22,
      step: 1,
      description: "Number of columns in the dot grid mesh.",
    },
    {
      name: "rows",
      type: "number",
      default: 9,
      min: 3,
      max: 22,
      step: 1,
      description: "Number of rows in the dot grid mesh.",
    },
    {
      name: "spacing",
      type: "number",
      default: 56,
      min: 20,
      max: 110,
      step: 1,
      description: "Distance in pixels between adjacent dot grid nodes.",
    },
    {
      name: "baseRadius",
      type: "number",
      default: 12,
      min: 3,
      max: 35,
      step: 1,
      description: "Resting size (radius in pixels) of the individual grid dots.",
    },
    {
      name: "springK",
      type: "number",
      default: 0.09,
      min: 0.01,
      max: 0.45,
      step: 0.005,
      description: "Spring stiffness / restoring tension constant.",
    },
    {
      name: "damp",
      type: "number",
      default: 0.78,
      min: 0.40,
      max: 0.98,
      step: 0.01,
      description: "Friction / damping factor applied to node velocities.",
    },
    {
      name: "gravityRadius",
      type: "number",
      default: 210,
      min: 50,
      max: 500,
      step: 5,
      description: "Influence radius of cursor interaction, in pixels.",
    },
    {
      name: "gravityMax",
      type: "number",
      default: 20,
      min: -60,
      max: 80,
      step: 2,
      description: "Max displacement force toward (positive) or away from (negative) cursor.",
    },
    {
      name: "bounceAmp",
      type: "number",
      default: 12,
      min: 2,
      max: 60,
      step: 1,
      description: "Base amplitude (strength) of wave displacement ripples.",
    },
    {
      name: "rowDelay",
      type: "number",
      default: 0.055,
      min: 0.010,
      max: 0.250,
      step: 0.005,
      description: "Delay in seconds for wave propagation between consecutive rows.",
    },
    {
      name: "decay",
      type: "number",
      default: 4.2,
      min: 0.5,
      max: 9.0,
      step: 0.1,
      description: "Exponential decay rate of the wave envelope over time.",
    },
    {
      name: "freq",
      type: "number",
      default: 13.0,
      min: 3.0,
      max: 30.0,
      step: 0.5,
      description: "Oscillation frequency of ripples, in radians per second.",
    },
    {
      name: "colSpread",
      type: "number",
      default: 0.65,
      min: 0.10,
      max: 2.00,
      step: 0.05,
      description: "Lateral Gaussian dispersion factor across columns.",
    },
    {
      name: "blur",
      type: "number",
      default: 8,
      min: 0,
      max: 25,
      step: 1,
      description: "CSS blur filter radius in pixels, driving the gooey liquid merge effect.",
    },
    {
      name: "contrast",
      type: "number",
      default: 28,
      min: 1,
      max: 50,
      step: 1,
      description: "CSS contrast filter threshold applied to sharpen blurred edges.",
    },
    {
      name: "dotColor",
      type: "color",
      default: "#ffffff",
      description: "Fill color hex code of the gooey grid dots.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#000000",
      description: "Substrate background color hex code.",
    },
    {
      name: "autoDrops",
      type: "boolean",
      default: true,
      description: "Whether periodic spontaneous raindrop ripples are enabled.",
    },
  ],
  presets: [
    {
      id: "liquid-mercury",
      label: "🪙 Liquid Mercury",
      config: {
        cols: 9,
        rows: 9,
        spacing: 56,
        baseRadius: 12,
        springK: 0.09,
        damp: 0.78,
        gravityRadius: 210,
        gravityMax: 20,
        rowDelay: 0.055,
        bounceAmp: 12,
        decay: 4.2,
        freq: 13.0,
        colSpread: 0.65,
        blur: 8,
        contrast: 28,
        dotColor: "#ffffff",
        bgColor: "#000000",
        autoDrops: true,
      },
    },
    {
      id: "molten-lava",
      label: "🌋 Molten Lava",
      config: {
        cols: 10,
        rows: 10,
        spacing: 50,
        baseRadius: 15,
        springK: 0.05,
        damp: 0.85,
        gravityRadius: 250,
        gravityMax: 35,
        rowDelay: 0.08,
        bounceAmp: 22,
        decay: 2.8,
        freq: 8.5,
        colSpread: 0.45,
        blur: 11,
        contrast: 24,
        dotColor: "#ff3700",
        bgColor: "#0d0200",
        autoDrops: true,
      },
    },
    {
      id: "neon-matrix",
      label: "🟢 Neon Matrix",
      config: {
        cols: 13,
        rows: 13,
        spacing: 44,
        baseRadius: 7,
        springK: 0.16,
        damp: 0.70,
        gravityRadius: 140,
        gravityMax: 45,
        rowDelay: 0.035,
        bounceAmp: 8,
        decay: 5.5,
        freq: 22.0,
        colSpread: 1.1,
        blur: 3,
        contrast: 16,
        dotColor: "#39ff14",
        bgColor: "#020702",
        autoDrops: true,
      },
    },
    {
      id: "cyber-plastik",
      label: "💖 Cyber Plastik",
      config: {
        cols: 8,
        rows: 8,
        spacing: 68,
        baseRadius: 20,
        springK: 0.07,
        damp: 0.80,
        gravityRadius: 280,
        gravityMax: -30,
        rowDelay: 0.06,
        bounceAmp: 28,
        decay: 2.2,
        freq: 7.0,
        colSpread: 0.5,
        blur: 14,
        contrast: 38,
        dotColor: "#e0007b",
        bgColor: "#020005",
        autoDrops: true,
      },
    },
    {
      id: "jellyfish-bloom",
      label: "🪼 Jellyfish Bloom",
      config: {
        cols: 8,
        rows: 14,
        spacing: 42,
        baseRadius: 9,
        springK: 0.04,
        damp: 0.92,
        gravityRadius: 190,
        gravityMax: 28,
        rowDelay: 0.14,
        bounceAmp: 16,
        decay: 1.8,
        freq: 5.5,
        colSpread: 0.35,
        blur: 9,
        contrast: 21,
        dotColor: "#00f0ff",
        bgColor: "#020212",
        autoDrops: true,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "Jean-Philippe Belley",
          role: "Original Creator",
          url: "https://jeanphilippebelley.com/",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Library",
          url: "https://react.dev",
        },
        {
          name: "Canvas API",
          role: "Rendering Engine",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API",
        },
      ],
    },
  ],
};
