import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const liquidNoiseConfig: ComponentConfig = {
  slug: "liquid-noise",
  name: "Liquid Noise",
  category: "background",
  tags: ["liquid", "noise", "fluid", "organic", "flow", "webgl"],
  componentPath: "app/meta/background/liquid/LiquidNoise.tsx",
  showDemoByDefault: true,
  demoVariant: "text",
  description: "React component that renders a continuously animating background using multi-color fluid domain warping. It features interactive cursor tracking for real - time fluid displacement along with an adjustable noise grain overlay.",
  npmPackageName: "@reactbytes/liquid-noise",
  version: "1.0.0",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0 || ^19.0.0",
    "react-dom": "^18.0.0 || ^19.0.0"
  },

  props: [
    {
      name: "colors",
      type: "string[]" as any,
      default: ["#312e81", "#5b21b6", "#9d174d", "#1e3a8a", "#115e59", "#4338ca"],
      description: "Array of up to 6 hex colors mapping out the fluid satin folds.",
    },
    {
      name: "backgroundColor",
      type: "color",
      default: "#030712",
      description: "Base canvas background tone underneath the liquid structure.",
    },
    {
      name: "speed",
      type: "number",
      default: 0.45,
      min: 0.1,
      max: 2.0,
      step: 0.05,
      description: "Tempo of the organic domain-warping folds.",
    },
    {
      name: "intensity",
      type: "number",
      default: 1.2,
      min: 0.2,
      max: 3.0,
      step: 0.1,
      description: "Luminance bloom and color blending power.",
    },
    {
      name: "grainIntensity",
      type: "number",
      default: 0.03,
      min: 0.0,
      max: 0.15,
      step: 0.01,
      description: "Intensity of the fine analog microfilm noise grain overlay.",
    },
    {
      name: "gradientSize",
      type: "number",
      default: 1.1,
      min: 0.2,
      max: 2.5,
      step: 0.1,
      description: "Scale modifier distorting the structural coordinates.",
    },
    {
      name: "gradientCount",
      type: "number",
      default: 6.0,
      min: 2,
      max: 6,
      step: 1,
      description: "The volume of complex color intersections evaluated.",
    },
    {
      name: "color1Weight",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 3.0,
      step: 0.1,
      description: "Mixing emphasis applied across odd index colors.",
    },
    {
      name: "color2Weight",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 3.0,
      step: 0.1,
      description: "Mixing emphasis applied across even index colors.",
    },
    {
      name: "uppercase",
      type: "boolean",
      default: false,
      description: "Forces nested child text elements to uppercase layouts.",
    },
  ],
  presets: [
    {
      id: "midnight-aurora",
      label: "Midnight Aurora (Default)",
      config: {
        colors: ["#312e81", "#5b21b6", "#9d174d", "#1e3a8a", "#115e59", "#4338ca"],
        backgroundColor: "#030712",
        speed: 0.45,
        intensity: 1.2,
        grainIntensity: 0.03,
        gradientSize: 1.1,
        gradientCount: 6.0,
        color1Weight: 1.0,
        color2Weight: 1.0,
        uppercase: false,
      },
    },
    {
      id: "cyberpunk-neon",
      label: "Cyberpunk Glow",
      config: {
        colors: ["#091e3a", "#701a75", "#017e8a", "#4a044e", "#06b6d4", "#d946ef"],
        backgroundColor: "#020617",
        speed: 0.7,
        intensity: 1.5,
        grainIntensity: 0.04,
        gradientSize: 0.9,
        gradientCount: 6.0,
        color1Weight: 1.2,
        color2Weight: 0.8,
        uppercase: true,
      },
    },
    {
      id: "emerald-forest",
      label: "Deep Obsidian Moss",
      config: {
        colors: ["#022c22", "#064e3b", "#14532d", "#0f766e", "#115e59", "#16a34a"],
        backgroundColor: "#022c22",
        speed: 0.3,
        intensity: 1.0,
        grainIntensity: 0.02,
        gradientSize: 1.3,
        gradientCount: 5.0,
        color1Weight: 1.0,
        color2Weight: 1.0,
        uppercase: false,
      },
    },
    {
      id: "rose-quartz",
      label: "Ethereal Pastel Quartz",
      config: {
        colors: ["#fda4af", "#f0abfc", "#cbd5e1", "#f472b6", "#e2e8f0", "#fae8ff"],
        backgroundColor: "#0f172a",
        speed: 0.35,
        intensity: 0.9,
        grainIntensity: 0.05,
        gradientSize: 1.2,
        gradientCount: 6.0,
        color1Weight: 1.0,
        color2Weight: 1.0,
        uppercase: false,
      },
    },
    {
      id: "solar-flare",
      label: "Magma & Amber",
      config: {
        colors: ["#451a03", "#78350f", "#9a3412", "#ea580c", "#ca8a04", "#f97316"],
        backgroundColor: "#0c0a09",
        speed: 0.5,
        intensity: 1.4,
        grainIntensity: 0.03,
        gradientSize: 1.0,
        gradientCount: 6.0,
        color1Weight: 1.1,
        color2Weight: 0.9,
        uppercase: true,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
    {
      title: "Core Technologies",
      items: [
        {
          name: "WebGL 2",
          role: "GPU Hardware Pipeline",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API",
        },
      ],
    },
  ],
};