import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const liquidNoiseConfig: ComponentConfig = {
  slug: "liquid-noise",
  name: "Liquid Noise",
  category: "background",
  componentPath: "app/meta/background/liquid/LiquidNoise.tsx",
  props: [
    {
      name: "colors",
      type: "string[]" as any,
      default: ["#f15a22", "#0a0e27", "#40e0d0", "#f15a22", "#0a0e27", "#40e0d0"],
      description: "Array of 6 hex colors that define the main gradient shades.",
    },
    {
      name: "speed",
      type: "number",
      default: 1.2,
      min: 0.1,
      max: 3.0,
      step: 0.1,
      description: "Speed of the swirling background animation.",
    },
    {
      name: "intensity",
      type: "number",
      default: 1.8,
      min: 0.5,
      max: 4.0,
      step: 0.1,
      description: "Intensity of the color bleeding and brightness.",
    },
    {
      name: "grainIntensity",
      type: "number",
      default: 0.08,
      min: 0.0,
      max: 0.3,
      step: 0.01,
      description: "Amount of film grain overlaid across the gradients.",
    },
    {
      name: "gradientSize",
      type: "number",
      default: 1.0,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "Radius modifier for the circular color blobs.",
    },
    {
      name: "gradientCount",
      type: "number",
      default: 6.0,
      min: 1,
      max: 12,
      step: 1,
      description: "Amount of gradient blobs interacting (max 12).",
    },
    {
      name: "color1Weight",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 5.0,
      step: 0.1,
      description: "Weighting bias applied to alternating bright colors.",
    },
    {
      name: "color2Weight",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 5.0,
      step: 0.1,
      description: "Weighting bias applied to alternating dark colors.",
    },
    {
      name: "darkNavy",
      type: "color",
      default: "#0a0e27",
      description: "Base/background color tone replacing absolute darkness.",
    },
    {
      name: "uppercase",
      type: "boolean",
      default: false,
      description: "Whether to force overlay text to uppercase.",
    },
  ],
  presets: [
    {
      id: "scheme1",
      label: "Scheme 1 (Orange & Navy)",
      config: {
        colors: ["#f15a22", "#0a0e27", "#f15a22", "#0a0e27", "#f15a22", "#0a0e27"],
        speed: 1.5,
        intensity: 1.8,
        grainIntensity: 0.08,
        gradientSize: 0.45,
        gradientCount: 12.0,
        color1Weight: 0.5,
        color2Weight: 1.8,
        darkNavy: "#0a0e27",
        uppercase: true,
      },
    },
    {
      id: "scheme2",
      label: "Scheme 2 (Turquoise & Coral)",
      config: {
        colors: ["#ff6c50", "#40e0d0", "#ff6c50", "#40e0d0", "#ff6c50", "#40e0d0"],
        speed: 1.2,
        intensity: 1.8,
        grainIntensity: 0.08,
        gradientSize: 1.0,
        gradientCount: 6.0,
        color1Weight: 1.0,
        color2Weight: 1.0,
        darkNavy: "#0a0e27",
        uppercase: false,
      },
    },
    {
      id: "scheme3",
      label: "Scheme 3 (Triple Blend)",
      config: {
        colors: ["#f15a22", "#0a0e27", "#40e0d0", "#f15a22", "#0a0e27", "#40e0d0"],
        speed: 1.2,
        intensity: 1.8,
        grainIntensity: 0.08,
        gradientSize: 1.0,
        gradientCount: 6.0,
        color1Weight: 1.0,
        color2Weight: 1.0,
        darkNavy: "#0a0e27",
        uppercase: false,
      },
    },
    {
      id: "scheme4",
      label: "Scheme 4 (Desert Mirage)",
      config: {
        colors: ["#f26633", "#2d6b6d", "#d1af9c", "#f26633", "#2d6b6d", "#d1af9c"],
        speed: 1.2,
        intensity: 1.8,
        grainIntensity: 0.08,
        gradientSize: 1.0,
        gradientCount: 6.0,
        color1Weight: 1.0,
        color2Weight: 1.0,
        darkNavy: "#ffffff",
        uppercase: false,
      },
    },
    {
      id: "scheme5",
      label: "Scheme 5 (Teal Darkness)",
      config: {
        colors: ["#f15a22", "#004238", "#f15a22", "#000000", "#f15a22", "#000000"],
        speed: 1.5,
        intensity: 1.8,
        grainIntensity: 0.08,
        gradientSize: 0.45,
        gradientCount: 12.0,
        color1Weight: 0.5,
        color2Weight: 1.8,
        darkNavy: "#0a0e27",
        uppercase: false,
      },
    },
  ],
  credits: [
    {
      title: "Component Origin",
      items: [
        {
          name: "React Bytes",
          role: "Implementation",
          url: "https://reactbytes.dev",
        },
        {
          name: "Made By Beings",
          role: "Concept",
          url: "https://madebybeings.com",
        },
      ],
    },
    {
      title: "Technologies",
      items: [
        {
          name: "WebGL 2",
          role: "Graphics API",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API",
        },
      ],
    },
  ],
};
