import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const velvetNoiseConfig: ComponentConfig = {
  slug: "velvet-noise",
  name: "Velvet Noise",
  category: "background",
  tags: ["velvet", "noise", "texture", "soft", "fabric"],
  componentPath: "app/meta/background/liquid/VelvetNoise.tsx",
  showDemoByDefault: true,
  demoVariant: "card",
  npmPackageName: "@reactbytes/velvet-noise",
  version: "1.0.0",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
    "react-dom": "^18.0.0",
  },
  description: "A GPU-accelerated WebGL background that generates flowing simplex noise with customizable colors, density, and animation. Designed for immersive hero sections, landing pages, and interactive visual experiences.",
  props: [
    {
      name: "cells",
      type: "number",
      default: 4.0,
      min: 1.0,
      max: 20.0,
      step: 0.5,
      description: "Number of horizontal columns or cells in the visual grid.",
    },
    {
      name: "stripes",
      type: "number",
      default: 40.0,
      min: 5.0,
      max: 150.0,
      step: 1.0,
      description: "Density frequency of simplex noise stripes.",
    },
    {
      name: "speed",
      type: "number",
      default: 0.5,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      description: "Speed multiplier for the organic flowing animation.",
    },
    {
      name: "chromatic",
      type: "number",
      default: 0.1,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      description:
        "RGB shift intensity creating the chromatic aberration offset.",
    },
    {
      name: "isPlaying",
      type: "boolean",
      default: true,
      description: "Toggle to pause or play the dynamic WebGL rendering loop.",
    },
    {
      name: "dpr",
      type: "number",
      default: 1.5,
      min: 1.0,
      max: 3.0,
      step: 0.5,
      description: "Resolution multiplier (Device Pixel Ratio scale factor).",
    },
    {
      name: "colorBg",
      type: "color",
      default: "#121212",
      description: "Hex color code for the deep base shader layer.",
    },
    {
      name: "colorFg",
      type: "color",
      default: "#000000",
      description: "Hex color code for the foreground simplex noise ripples.",
    },
  ],
  presets: [
    {
      id: "darkGreyVelvet",
      label: "Dark Velvet (Default)",
      config: {
        cells: 4.0,
        stripes: 40.0,
        speed: 0.1,
        chromatic: 0.1,
        colorBg: "#ffffffff",
        colorFg: "#000000",
        isPlaying: true,
        dpr: 1.5,
      },
    },
    {
      id: "obsidianChroma",
      label: "Obsidian Aberration",
      config: {
        cells: 8.0,
        stripes: 85.0,
        speed: 0.2,
        chromatic: 0.35,
        colorBg: "#0a0a0a",
        colorFg: "#1e1e1e",
        isPlaying: true,
        dpr: 1.5,
      },
    },
    {
      id: "charcoalStatic",
      label: "Charcoal Ripples",
      config: {
        cells: 2.0,
        stripes: 15.0,
        speed: 0.3,
        chromatic: 0.05,
        colorBg: "#1c1c1c",
        colorFg: "#050505",
        isPlaying: true,
        dpr: 1.5,
      },
    },
    {
      id: "abyssQuantum",
      label: "Extreme Horizon",
      config: {
        cells: 14.0,
        stripes: 130.0,
        speed: 0.4,
        chromatic: 0.6,
        colorBg: "#151516",
        colorFg: "#000000",
        isPlaying: true,
        dpr: 1.5,
      },
    },
    {
      id: "amethystHaze",
      label: "Amethyst Haze",
      config: {
        cells: 6.0,
        stripes: 60.0,
        speed: 0.8,
        chromatic: 0.25,
        colorBg: "#0f051d",
        colorFg: "#2a0f4e",
        isPlaying: true,
        dpr: 1.5,
      },
    },
    {
      id: "emeraldAurora",
      label: "Emerald Aurora",
      config: {
        cells: 5.0,
        stripes: 50.0,
        speed: 0.6,
        chromatic: 0.15,
        colorBg: "#061310",
        colorFg: "#0d3c33",
        isPlaying: true,
        dpr: 1.5,
      },
    },
    {
      id: "oceanicAbyss",
      label: "Oceanic Abyss",
      config: {
        cells: 4.5,
        stripes: 45.0,
        speed: 0.7,
        chromatic: 0.3,
        colorBg: "#020b14",
        colorFg: "#0b2545",
        isPlaying: true,
        dpr: 1.5,
      },
    },
    {
      id: "solarEclipse",
      label: "Solar Crimson",
      config: {
        cells: 3.5,
        stripes: 35.0,
        speed: 0.4,
        chromatic: 0.12,
        colorBg: "#1a0404",
        colorFg: "#3d0a0a",
        isPlaying: true,
        dpr: 1.5,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
    {
      title: "Libraries",
      items: [
        {
          name: "WebGL2",
          role: "Renderer API",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API",
        },
      ],
    },
  ],
};
