import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const tectonicTrackTextConfig: ComponentConfig = {
  slug: "tectonic-track-text",
  name: "Tectonic Track Text",
  category: "text",
  tags: ["tectonic", "track", "slide", "mechanical", "reveal"],
  componentPath: "app/meta/text/TectonicTrackText/TectonicTrackText.tsx",
  npmPackageName: "@reactbytes/tectonic-track-text",
  version: "1.0.0",
  props: [
    {
      name: "text",
      type: "string",
      default: "TECTONIC",
      description: "The word/text to render and animate.",
    },
    {
      name: "fontSize",
      type: "number",
      default: 75,
      min: 40,
      max: 140,
      step: 5,
      description: "Font size in pixels defining absolute canvas layout size.",
    },
    {
      name: "maxTrackingExpansion",
      type: "number",
      default: 35,
      min: 5,
      max: 100,
      step: 5,
      description:
        "Maximum letter spacing tracking expansion value (in pixels).",
    },
    {
      name: "maxScaleX",
      type: "number",
      default: 1.25,
      min: 1.0,
      max: 2.5,
      step: 0.05,
      description: "Maximum width scale multiplier applied under tension.",
    },
    {
      name: "influenceRadius",
      type: "number",
      default: 120,
      min: 40,
      max: 300,
      step: 10,
      description: "Horizontal mouse proximity interaction threshold.",
    },
    {
      name: "stiffness",
      type: "number",
      default: 0.08,
      min: 0.01,
      max: 0.3,
      step: 0.01,
      description: "Elastic tracking snap stiffness coefficient.",
    },
    {
      name: "damping",
      type: "number",
      default: 0.74,
      min: 0.5,
      max: 0.99,
      step: 0.01,
      description: "Spring system damping friction factor.",
    },
    {
      name: "color",
      type: "color",
      default: "#ffffff",
      description: "Foreground color of the characters.",
    },
    {
      name: "lineColor",
      type: "color",
      default: "rgba(255, 255, 255, 0.15)",
      description: "Color of the alignment track baseline and ticks.",
    },
  ],
  presets: [
    {
      id: "standard",
      label: "Standard Elastic (Default)",
      config: {
        text: "TECTONIC",
        fontSize: 75,
        color: "#ffffff",
        lineColor: "rgba(255, 255, 255, 0.15)",
        maxTrackingExpansion: 35,
        maxScaleX: 1.25,
        influenceRadius: 120,
        stiffness: 0.08,
        damping: 0.74,
      },
    },
    {
      id: "lens",
      label: "Lensing Effect",
      config: {
        text: "GRAVITATION",
        fontSize: 75,
        color: "#a78bfa",
        lineColor: "rgba(167, 139, 250, 0.3)",
        maxTrackingExpansion: 5,
        maxScaleX: 2.5,
        influenceRadius: 100,
        stiffness: 0.3,
        damping: 0.5,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
  ],
  staticProps: {},
};
