"use client";

import dynamic from "next/dynamic";
import React from "react";

export const ComponentMap: Record<string, React.ComponentType<any>> = {
  "reveal-under": dynamic(() => import("../meta/text/TextEnter/RevealUnder")),
  "fall-down": dynamic(() => import("../meta/text/TextEnter/FallDown")),
  "variable-weight": dynamic(() => import("../meta/text/TextEnter/VariableWeightText")),
  "aperture-text": dynamic(() => import("../meta/text/ApertureText/ApertureText")),
  "axial-shear-text": dynamic(() => import("../meta/text/AxialShearText/AxialShearText")),
  "blur-text": dynamic(() => import("../meta/text/BlurText/BlurText")),
  "elastic-reveal": dynamic(() => import("../meta/text/Hover/ElasticReveal")),
  "focal-blur": dynamic(() => import("../meta/text/Interactive/FocalBlurText")),
  "granular-text": dynamic(() => import("../meta/text/Interactive/GranularText")),
  "magnetic-text": dynamic(() => import("../meta/text/Interactive/MagneticText")),
  "shatter-text": dynamic(() => import("../meta/text/Interactive/ShatterText")),
  "wave-text": dynamic(() => import("../meta/text/Interactive/WaveText")),
  "gooey-morph": dynamic(() => import("../meta/text/Morph/GooeyMorph")),
  "swarm-text": dynamic(() => import("../meta/text/SwarmText/SwarmText")),
  "blur-in": dynamic(() => import("../meta/text/TextEnter/BlurIn")),
  "scramble-reveal": dynamic(() => import("../meta/text/TextEnter/ScrambleReveal")),
  "volumetric-text": dynamic(() => import("../meta/text/VolumetricText/VolumetricText")),
  "keyboard-text": dynamic(() => import("../meta/text/keyboard/KeyboardText")),
  "kinetic-text": dynamic(() => import("../meta/text/Interactive/KineticText")),
  "tectonic-lattice-text": dynamic(() => import("../meta/text/TectonicLatticeText/TectonicLatticeText")),
  "stratum-text": dynamic(() => import("../meta/text/StratumText/StratumText")),
  "helix-text": dynamic(() => import("../meta/text/HelixText/HelixText")),
  "phase-shell-text": dynamic(() => import("../meta/text/PhaseShellText/PhaseShellText")),
  "scaffold-text": dynamic(() => import("../meta/text/ScaffoldText/ScaffoldText")),
  "tectonic-track-text": dynamic(() => import("../meta/text/TectonicTrackText/TectonicTrackText")),
  "atmospheric-drift": dynamic(() => import("../meta/background/AtmosphericDrift/AtmosphericDrift")),
  "ascii-wave": dynamic(() => import("../meta/background/wave/AsciiWave/AsciiWave")),
  "magnetic-dots": dynamic(() => import("../meta/background/dotted/MagneticDotMesh")),
  "bubble-gradient": dynamic(() => import("../meta/background/gradient/BubbleGradient")),
  "fractal-background": dynamic(() => import("../meta/background/fractal/FractalBackground")),
  "cellular-automata": dynamic(() => import("../meta/background/cellular/CellularAutomataBackground")),
  "hive-mind": dynamic(() => import("../meta/background/flowfield/HiveMind")),
  "helon-braid": dynamic(() => import("../meta/background/wave/HelonBraid/HelonBraid")),
  "perlin-smoke": dynamic(() => import("../meta/background/gradient/PerlinSmoke")),
  "metallic-twirl": dynamic(() => import("../meta/background/metallic/MetallicTwirl")),
  "liquid-noise": dynamic(() => import("../meta/background/liquid/LiquidNoise")),
  "velvet-noise": dynamic(() => import("../meta/background/liquid/VelvetNoise")),
  "fbm-noise": dynamic(() => import("../meta/background/liquid/FbmNoise")),
  "eye-matrix": dynamic(() => import("../meta/background/dotted/EyeMatrix")),
  "poisson-noise": dynamic(() => import("../meta/background/dotted/PoissonNoise")),
  "liquid-grid": dynamic(() => import("../meta/background/liquid/LiquidGrid")),
  "iridescent-gradient": dynamic(() => import("../meta/background/gradient/IridescentGradient")),
  "kaleidoscopic": dynamic(() => import("../meta/background/fractal/Kaleidoscopic")),
  "dotted-vortex": dynamic(() => import("../meta/background/dotted/DottedVortex")),
  "concentric-waves": dynamic(() => import("../meta/background/wave/ConcentricWaves/ConcentricWaves")),
};
