import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const voidOrbConfig: ComponentConfig = {
  slug: "void-orb",
  name: "Void Orb",
  category: "background",
  tags: ["void", "orb", "dark", "energy", "glow", "space"],
  componentPath: "app/meta/background/space/VoidOrb.tsx",
  description: "A highly optimized, interactive WebGL void orb background component.",
  npmPackageName: "@reactbytes/void-orb",
  version: "1.0.1",
  dependencies: {
    "three": "^0.184.0"
  },
  peerDependencies: {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  showDemoByDefault: true,
  demoVariant: "hero",
  props: [
    {
      name: "primaryColor",
      type: "color",
      default: "#ffffff",
      description: "Primary highlights emission color (Hex).",
    },
    {
      name: "secondaryColor",
      type: "color",
      default: "#7c7c7c",
      description: "Secondary swirly accent color (Hex).",
    },
    {
      name: "accentColor",
      type: "color",
      default: "#000000",
      description: "Deep stop void background backdrop color (Hex).",
    },
    {
      name: "fractalScale",
      type: "number",
      default: 0.35,
      min: 0.05,
      max: 1.5,
      step: 0.01,
      description: "Orb dimension sizing scale factor.",
    },
    {
      name: "fractalX",
      type: "number",
      default: 0.0,
      min: -1.5,
      max: 1.5,
      step: 0.05,
      description: "Grid center X coordinate offset.",
    },
    {
      name: "fractalY",
      type: "number",
      default: 0.0,
      min: -1.5,
      max: 1.5,
      step: 0.05,
      description: "Grid center Y coordinate offset.",
    },
    {
      name: "lightCount",
      type: "number",
      default: 1,
      min: 1,
      max: 8,
      step: 1,
      description: "The total active orbiting light sources (1 to 8).",
    },
    {
      name: "lightIntensity",
      type: "number",
      default: 1.2,
      min: 0.2,
      max: 3.0,
      step: 0.1,
      description: "Luminous brightness multiplier of the lights.",
    },
    {
      name: "lightSpeed",
      type: "number",
      default: 0.8,
      min: 0.0,
      max: 4.0,
      step: 0.1,
      description: "Angular speed velocity factor of orbit paths.",
    },
    {
      name: "grainStrength",
      type: "number",
      default: 0.16,
      min: 0.0,
      max: 0.4,
      step: 0.01,
      description: "Film grain noise opacity/strength (0.0 to 0.4).",
    },
    {
      name: "grainSize",
      type: "number",
      default: 3.5,
      min: 1.0,
      max: 8.0,
      step: 0.1,
      description: "Frequency density scale of film grain pixels.",
    },
    {
      name: "animationSpeed",
      type: "number",
      default: 0.015,
      min: 0.0,
      max: 0.1,
      step: 0.002,
      description: "Sinusoidal warp morphing speed velocity.",
    },
    {
      name: "autoRotate",
      type: "boolean",
      default: true,
      description: "Whether spatial coordinate rotation is enabled.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Monochrome Shadow",
      config: {
        primaryColor: "#ffffff",
        secondaryColor: "#7c7c7c",
        accentColor: "#000000",
        fractalScale: 0.35,
        fractalX: 0.0,
        fractalY: 0.0,
        lightCount: 1,
        lightIntensity: 1.2,
        lightSpeed: 0.8,
        grainStrength: 0.16,
        grainSize: 3.5,
        animationSpeed: 0.015,
        autoRotate: true,
      },
    },
    {
      id: "solar",
      label: "Solar Flare",
      config: {
        primaryColor: "#ff9e00",
        secondaryColor: "#ff0055",
        accentColor: "#220000",
        fractalScale: 0.5,
        fractalX: 0.0,
        fractalY: 0.0,
        lightCount: 3,
        lightIntensity: 1.5,
        lightSpeed: 2.0,
        grainStrength: 0.12,
        grainSize: 4.0,
        animationSpeed: 0.03,
        autoRotate: true,
      },
    },
    {
      id: "nebula",
      label: "Deep Nebula",
      config: {
        primaryColor: "#00f0ff",
        secondaryColor: "#aa00ff",
        accentColor: "#050015",
        fractalScale: 0.28,
        fractalX: 0.0,
        fractalY: 0.0,
        lightCount: 4,
        lightIntensity: 1.8,
        lightSpeed: 1.2,
        grainStrength: 0.18,
        grainSize: 2.8,
        animationSpeed: 0.01,
        autoRotate: true,
      },
    },
    {
      id: "emerald",
      label: "Emerald Matrix",
      config: {
        primaryColor: "#00ff66",
        secondaryColor: "#003311",
        accentColor: "#000500",
        fractalScale: 0.45,
        fractalX: 0.0,
        fractalY: 0.0,
        lightCount: 2,
        lightIntensity: 1.0,
        lightSpeed: 1.5,
        grainStrength: 0.22,
        grainSize: 5.0,
        animationSpeed: 0.025,
        autoRotate: true,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
    {
      title: "Inspiration",
      items: [
        {
          name: "Filip Zrnzević",
          role: "Digital Artist",
          url: "https://x.com/filipz",
        },
      ],
    },
    {
      title: "Libraries Used",
      items: [
        {
          name: "Three.js",
          role: "WebGL Framework",
          url: "https://threejs.org",
        }
      ],
    },
  ],
};
