import { ComponentDatabase } from "../app/registry/ComponentDatabase";
import * as fs from "fs";
import * as path from "path";

async function run() {
  console.log("[*] Generating chunked build-time Component Code Database...");

  const chunksDir = path.join(__dirname, "../app/registry/code-chunks");
  
  // Recreate the chunks directory to ensure it is clean
  if (fs.existsSync(chunksDir)) {
    fs.rmSync(chunksDir, { recursive: true, force: true });
  }
  fs.mkdirSync(chunksDir, { recursive: true });

  const slugs: string[] = [];

  for (const component of ComponentDatabase) {
    const fullPath = path.resolve(__dirname, "..", component.componentPath);
    if (!fs.existsSync(fullPath)) {
      console.warn(`[!] Warning: Component file not found at path: ${component.componentPath}`);
      continue;
    }

    try {
      const code = fs.readFileSync(fullPath, "utf-8");
      const stat = fs.statSync(fullPath);
      const lastModified = stat.mtime.toISOString();

      // Write standalone chunk file
      const chunkFilePath = path.join(chunksDir, `${component.slug}.ts`);
      const chunkContent = `// Auto-generated. Do not edit.
export const code = ${JSON.stringify(code)};
export const lastModified = ${JSON.stringify(lastModified)};
`;
      fs.writeFileSync(chunkFilePath, chunkContent, "utf-8");
      slugs.push(component.slug);
    } catch (err) {
      console.error(`[✗] Failed to read component at ${component.componentPath}:`, err);
    }
  }

  const outputPath = path.join(__dirname, "../app/registry/ComponentCodeDatabase.ts");
  
  // Export a registry map of dynamic functions using ES import() syntax
  const importsContent = slugs
    .map((slug) => `  "${slug}": () => import("./code-chunks/${slug}")`)
    .join(",\n");

  const fileContent = `// This file is auto-generated by scripts/generate-code-database.ts at build-time.
// Do not modify this file manually.

export const ComponentCodeDatabase: Record<
  string,
  () => Promise<{ code: string; lastModified: string }>
> = {
${importsContent}
};
`;

  fs.writeFileSync(outputPath, fileContent, "utf-8");
  console.log(`[✓] Successfully generated Component Code Database with ${slugs.length} lazy-loaded chunks at: ${outputPath}`);
}

run().catch((err) => {
  console.error("[✗] Failed to generate component code database:", err);
  process.exit(1);
});
