import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const hiveMindConfig: ComponentConfig = {
  slug: "hive-mind",
  name: "Hive Mind",
  category: "background",
  tags: ["hive", "flow", "field", "agents", "particles", "swarm"],
  componentPath: "app/meta/background/flowfield/HiveMind.tsx",
  showDemoByDefault: true,
  demoVariant: "card",
  props: [
    {
      name: "count",
      type: "number",
      default: 3000,
      min: 100,
      max: 15000,
      step: 100,
      description: "The total number of particles on screen.",
    },
    {
      name: "noiseScale",
      type: "number",
      default: 650,
      min: 10,
      max: 3000,
      step: 10,
      description: "Zoom level of the noise field. Lower is more chaotic.",
    },
    {
      name: "noiseSpeed",
      type: "number",
      default: 0.005,
      min: 0,
      max: 0.1,
      step: 0.001,
      description: "Speed at which the flow field evolves over time.",
    },
    {
      name: "velocity",
      type: "number",
      default: 5.0,
      min: 0.1,
      max: 30.0,
      step: 0.1,
      description: "Movement speed of the particles.",
    },
    {
      name: "opacity",
      type: "number",
      default: 0.05,
      min: 0.001,
      max: 0.5,
      step: 0.001,
      description:
        "Trailing effect intensity (tail opacity). Lower is longer trails.",
    },
    {
      name: "radius",
      type: "number",
      default: 2.0,
      min: 0.1,
      max: 15.0,
      step: 0.1,
      description: "Base size multiplier for the particles.",
    },
    {
      name: "color1",
      type: "color",
      default: "#4b97a2",
      description: "Primary particle color.",
    },
    {
      name: "color2",
      type: "color",
      default: "#e94b3c",
      description: "Secondary particle color.",
    },
    {
      name: "backgroundColor",
      type: "color",
      default: "#000000",
      description: "Canvas background color.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Classic Hive",
      config: {
        count: 3000,
        noiseScale: 650,
        noiseSpeed: 0.005,
        velocity: 5,
        opacity: 0.05,
        radius: 2,
        color1: "#4b97a2",
        color2: "#e94b3c",
        backgroundColor: "#000000",
      },
    },
    {
      id: "electric",
      label: "Electric Storm",
      config: {
        count: 5000,
        noiseScale: 200,
        noiseSpeed: 0.02,
        velocity: 10,
        opacity: 0.1,
        radius: 1,
        color1: "#00f2ff",
        color2: "#7000ff",
        backgroundColor: "#050010",
      },
    },
    {
      id: "ghost",
      label: "Ghostly Flow",
      config: {
        count: 2000,
        noiseScale: 1200,
        noiseSpeed: 0.001,
        velocity: 3,
        opacity: 0.02,
        radius: 3,
        color1: "#ffffff",
        color2: "#999999",
        backgroundColor: "#111111",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "Neo Hive Mind",
          role: "Visual Designer",
          url: "https://codepen.io/iam-noob/pen/zYrjXzY",
        },
        {
          name: "React Bytes",
          role: "Collection",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Framework",
          url: "https://react.dev",
        },
        {
          name: "Canvas API",
          role: "Graphics",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API",
        },
      ],
    },
  ],
};
