import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const volumetricTextConfig: ComponentConfig = {
  slug: "volumetric-text",
  name: "Volumetric Text",
  category: "text",
  tags: ["volumetric", "3d", "depth", "shadow", "extrude"],
  componentPath: "app/meta/text/VolumetricText/VolumetricText.tsx",
  props: [
    {
      name: "text",
      type: "string",
      default: "All hail Rameez",
      description: "The text content or SVG string to render.",
    },
    {
      name: "textSize",
      type: "number",
      default: 300,
      min: 10,
      max: 800,
      step: 10,
      description: "Size of the text in the canvas texture.",
    },
    {
      name: "shapeScale",
      type: "number",
      default: 0.3,
      min: 0.05,
      max: 1.5,
      step: 0.01,
      description: "Scale of the shape relative to screen dimensions.",
    },
    {
      name: "invertShape",
      type: "boolean",
      default: true,
      description: "Whether to invert the shape mask (dark vs light).",
    },
    {
      name: "addNoise",
      type: "boolean",
      default: true,
      description: "Add fractal noise (FBM) to distort the light rays.",
    },
    {
      name: "samples",
      type: "number",
      default: 12,
      min: 1,
      max: 32,
      step: 1,
      description:
        "Number of samples along the ray path (requires shader compilation).",
    },
    {
      name: "octaves",
      type: "number",
      default: 1,
      min: 1,
      max: 5,
      step: 1,
      description:
        "Number of octaves for FBM noise (requires shader compilation).",
    },
    {
      name: "lightStrength",
      type: "number",
      default: 3.5,
      min: 0,
      max: 10,
      step: 0.1,
      description: "Focus/strength of the volumetric light source.",
    },
    {
      name: "exposure",
      type: "number",
      default: 0.35,
      min: 0,
      max: 2,
      step: 0.05,
      description: "Overall intensity / brightness exposure of the rays.",
    },
    {
      name: "decay",
      type: "number",
      default: 0.96,
      min: 0.5,
      max: 1.0,
      step: 0.01,
      description: "How fast the light rays decay over distance (0 to 1).",
    },
    {
      name: "falloff",
      type: "number",
      default: 0.5,
      min: 0,
      max: 2,
      step: 0.05,
      description: "Radial falloff rate of the volumetric light color.",
    },
    {
      name: "density",
      type: "number",
      default: 0.98,
      min: 0,
      max: 3,
      step: 0.05,
      description: "Density of the ray samples (step spacing).",
    },
    {
      name: "weight",
      type: "number",
      default: 0.25,
      min: 0,
      max: 1,
      step: 0.01,
      description: "Weight factor applied to each light sample.",
    },
    {
      name: "lightColor",
      type: "color",
      default: "#ffff66",
      description: "Hex code for the source light color.",
    },
    {
      name: "falloffColor",
      type: "color",
      default: "#00ccff",
      description: "Hex code for the surrounding falloff color.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#004040",
      description: "Hex code for the background scene color.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Style",
      config: {
        text: "All hail Rameez",
        textSize: 300,
        shapeScale: 0.3,
        invertShape: true,
        addNoise: true,
        decay: 0.96,
        exposure: 0.35,
        lightStrength: 3.5,
        lightColor: "#ffff66",
        falloffColor: "#00ccff",
        bgColor: "#004040",
        falloff: 0.5,
        density: 0.98,
        weight: 0.25,
        samples: 12,
        octaves: 1,
      },
    },
    {
      id: "cyberpunk",
      label: "Cyberpunk Fog",
      config: {
        text: "CYBER",
        textSize: 240,
        shapeScale: 0.3,
        invertShape: true,
        addNoise: true,
        decay: 0.98,
        exposure: 0.6,
        lightStrength: 4.0,
        lightColor: "#ff007f",
        falloffColor: "#00ffff",
        bgColor: "#0a0a16",
        falloff: 0.7,
        density: 1.0,
        weight: 0.3,
        samples: 16,
        octaves: 2,
      },
    },
    {
      id: "solar",
      label: "Solar Flare",
      config: {
        text: "SOLAR",
        textSize: 220,
        shapeScale: 0.3,
        invertShape: true,
        addNoise: true,
        decay: 0.95,
        exposure: 0.5,
        lightStrength: 4.5,
        lightColor: "#ff7f00",
        falloffColor: "#ff0000",
        bgColor: "#160500",
        falloff: 0.4,
        density: 0.95,
        weight: 0.35,
        samples: 12,
        octaves: 3,
      },
    },
    {
      id: "forest",
      label: "Forest Glow",
      config: {
        text: "ECO",
        textSize: 300,
        shapeScale: 0.3,
        invertShape: true,
        addNoise: true,
        decay: 0.97,
        exposure: 0.4,
        lightStrength: 3.2,
        lightColor: "#aaff55",
        falloffColor: "#004411",
        bgColor: "#021c08",
        falloff: 0.6,
        density: 0.98,
        weight: 0.2,
        samples: 12,
        octaves: 1,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "WebGL God Rays",
          role: "Visual Reference & Shader",
          url: "https://codepen.io/soju/pen/wvvMMrP",
        },
        {
          name: "Three.js",
          role: "3D Rendering Library",
          url: "https://threejs.org/",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Framework",
          url: "https://react.dev",
        },
        {
          name: "Three.js",
          role: "WebGL abstraction",
          url: "https://threejs.org",
        },
      ],
    },
  ],
  staticProps: {
    className: "w-full h-full",
  },
};
