import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const asciiWaveConfig: ComponentConfig = {
  slug: "ascii-wave",
  name: "ASCII Wave",
  category: "background",
  componentPath: "app/meta/background/wave/AsciiWave/AsciiWave.tsx",
  props: [
    {
      name: "gap",
      type: "number",
      default: 40,
      min: 10,
      max: 100,
      step: 5,
      description: "Distance between each character in the grid.",
    },
    {
      name: "radiusVmin",
      type: "number",
      default: 30,
      min: 10,
      max: 100,
      step: 5,
      description: "Radius of influence from the mouse pointer (in vmin).",
    },
    {
      name: "speedIn",
      type: "number",
      default: 0.5,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "Speed factor when a character is scaling up.",
    },
    {
      name: "speedOut",
      type: "number",
      default: 0.6,
      min: 0.1,
      max: 2.0,
      step: 0.1,
      description: "Speed factor when a character is scaling down to rest.",
    },
    {
      name: "restScale",
      type: "number",
      default: 0.09,
      min: 0.01,
      max: 0.5,
      step: 0.01,
      description: "The base scale of characters when at rest.",
    },
    {
      name: "minHoverScale",
      type: "number",
      default: 1.0,
      min: 0.5,
      max: 3.0,
      step: 0.1,
      description: "Minimum scale a character can reach when hovered.",
    },
    {
      name: "maxHoverScale",
      type: "number",
      default: 3.0,
      min: 1.0,
      max: 6.0,
      step: 0.1,
      description: "Maximum scale a character can reach when hovered.",
    },
    {
      name: "waveSpeed",
      type: "number",
      default: 1200,
      min: 500,
      max: 3000,
      step: 100,
      description: "Speed of the click wave propagation.",
    },
    {
      name: "waveWidth",
      type: "number",
      default: 180,
      min: 50,
      max: 500,
      step: 10,
      description: "Thickness of the click wave.",
    },
    {
      name: "chars",
      type: "select",
      default: "@#$%&*+=?AX01∑∆πΩ",
      options: [
        { id: "@#$%&*+=?AX01∑∆πΩ", label: "@#$%&*+=?AX01∑∆πΩ" },
        { id: "☰☱☲☳☴☵☶☷", label: "☰☱☲☳☴☵☶☷" },
        { id: "▤▥▦▧▨▩", label: "▤▥▦▧▨▩" },
        { id: "♚♛♜♝♞♟♔♕♖♗♘♙", label: "♚♛♜♝♞♟♔♕♖♗♘♙" },
        { id: "▖▗▘▙▚▛▜▝▞▟■", label: "▖▗▘▙▚▛▜▝▞▟■" },
        { id: "◐◑◒◓◔◕", label: "◐◑◒◓◔◕" },
        { id: "◰◱◲◳◴◵◶◷", label: "◰◱◲◳◴◵◶◷" },
        { id: "10", label: "10" },
        { id: "✻✼❄❅❆❇❈❉❊❋", label: "✻✼❄❅❆❇❈❉❊❋" },
        { id: "⣿⣷⣯⣟⡿⢿⣻⣽", label: "⣿⣷⣯⣟⡿⢿⣻⣽" },
        { id: "αβγδεζηθικλμ", label: "αβγδεζηθικλμ" },
        { id: "⚀⚁⚂⚃⚄⚅", label: "⚀⚁⚂⚃⚄⚅" },
        { id: "ᚠᚡᚢᚣᚤᚥᚦᚧᚨᚩᚪᚫ", label: "ᚠᚡᚢᚣᚤᚥᚦᚧᚨᚩᚪᚫ" },
        { id: "◢◣◤◥", label: "◢◣◤◥" },
        { id: "♠♥♦♣♤♢♧♡", label: "♠♥♦♣♤♢♧♡" },
        { id: "✽✾✿❀❁❂❃", label: "✽✾✿❀❁❂❃" },
        { id: "┌┐└┘├┤┬┴┼─", label: "┌┐└┘├┤┬┴┼─" },
        { id: "╓╔╕╖╗╘╙╚╛╜╝", label: "╓╔╕╖╗╘╙╚╛╜╝" },
        { id: "⋐⋑⋒⋓", label: "⋐⋑⋒⋓" },
      ],
      description: "Characters to use in the wave grid.",
    },
    {
      name: "colorMode",
      type: "boolean",
      default: true,
      description: "Toggle between using the provided palette or grayscale equivalents.",
    },
    {
      name: "backgroundColor",
      type: "color",
      default: "#050505",
      description: "Canvas and container background color.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Style",
      config: {
        gap: 40,
        radiusVmin: 30,
        speedIn: 0.5,
        speedOut: 0.6,
        restScale: 0.09,
        minHoverScale: 1,
        maxHoverScale: 3,
        waveSpeed: 1200,
        waveWidth: 180,
        chars: "@#$%&*+=?AX01∑∆πΩ",
        colorMode: true,
        backgroundColor: "#050505",
      },
    },
    {
      id: "dense",
      label: "Dense Matrix",
      config: {
        gap: 20,
        radiusVmin: 20,
        speedIn: 0.7,
        speedOut: 0.8,
        restScale: 0.05,
        minHoverScale: 1.5,
        maxHoverScale: 4,
        waveSpeed: 800,
        waveWidth: 120,
        chars: "01",
        colorMode: false,
        backgroundColor: "#111111",
      },
    },
    {
      id: "sparse",
      label: "Sparse & Fast",
      config: {
        gap: 60,
        radiusVmin: 50,
        speedIn: 0.3,
        speedOut: 0.4,
        restScale: 0.15,
        minHoverScale: 1.2,
        maxHoverScale: 2.5,
        waveSpeed: 2000,
        waveWidth: 300,
        chars: "XO+-",
        colorMode: true,
        backgroundColor: "#000000",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "React Bytes",
          role: "Collection",
          url: "https://reactbytes.dev",
        },
      ],
    },
  ],
};
