import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const swarmTextConfig: ComponentConfig = {
  slug: "swarm-text",
  name: "Swarm Text",
  category: "text",
  tags: ["swarm", "particles", "scatter", "assemble", "chaos"],
  componentPath: "app/meta/text/SwarmText/SwarmText.tsx",
  npmPackageName: "@reactbytes/swarm-text",
  version: "1.0.0",
  props: [
    {
      name: "texts",
      type: "string",
      default: "Developer, Designer, Philosopher, Physicist",
      description: "Array of words to rotate/morph through (comma-separated).",
    },
    {
      name: "delay",
      type: "number",
      default: 3000,
      min: 1000,
      max: 10000,
      step: 500,
      description:
        "Duration in milliseconds to display each word before swapping.",
    },
    {
      name: "fontSize",
      type: "number",
      default: 100,
      min: 24,
      max: 100,
      step: 2,
      description: "Font size of the dynamic text on the canvas (pixels).",
    },
    {
      name: "friction",
      type: "number",
      default: 0.85,
      min: 0.5,
      max: 0.98,
      step: 0.01,
      description: "Friction / damping coefficient for the particle movements.",
    },
    {
      name: "springStiffness",
      type: "number",
      default: 0.08,
      min: 0.01,
      max: 0.3,
      step: 0.01,
      description:
        "Spring stiffness factor pulling particles back to text target points.",
    },
    {
      name: "particleSize",
      type: "number",
      default: 0.9,
      min: 0.5,
      max: 5,
      step: 0.1,
      description: "Base radius of the rendered particles.",
    },
    {
      name: "step",
      type: "number",
      default: 2,
      min: 2,
      max: 6,
      step: 1,
      description:
        "Grid pixel sampling step. Lower values increase particle density but decrease performance.",
    },
    {
      name: "mouseRepel",
      type: "boolean",
      default: true,
      description:
        "Enables particle repulsion when hovering with the cursor or dragging.",
    },
    {
      name: "repelRadius",
      type: "number",
      default: 60,
      min: 20,
      max: 150,
      step: 5,
      description: "Radius of influence around the mouse in pixels.",
    },
    {
      name: "repelStrength",
      type: "number",
      default: 4.0,
      min: 0.5,
      max: 10.0,
      step: 0.5,
      description:
        "Repelling force factor pushing particles away from the mouse.",
    },
    {
      name: "textColor",
      type: "color",
      default: "#E8EAF0",
      description: "Hex or CSS color for the text particles.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Swarm",
      config: {
        texts: "Developer, Designer, Philosopher, Physicist",
        fontSize: 100,
        textColor: "#E8EAF0",
        friction: 0.85,
        springStiffness: 0.08,
        particleSize: 0.9,
        repelRadius: 60,
        repelStrength: 4.0,
        mouseRepel: true,
        step: 2,
      },
    },
    {
      id: "cyberpunk",
      label: "Cyberpunk Terminal",
      config: {
        texts: "ONLINE, ENCRYPTED, SECURE, SYSTEM",
        fontSize: 90,
        textColor: "#10B981",
        friction: 0.8,
        springStiffness: 0.3,
        particleSize: 2,
        repelRadius: 150,
        repelStrength: 10,
        mouseRepel: true,
        step: 6,
      },
    },
    {
      id: "sunset",
      label: "Warm Sunset",
      config: {
        texts: "Innovate, Inspire, Create, Connect",
        fontSize: 67,
        textColor: "#F59E0B",
        friction: 0.5,
        springStiffness: 0.06,
        particleSize: 1.5,
        repelRadius: 50,
        repelStrength: 3.0,
        mouseRepel: true,
        step: 3,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
  ],
};