import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const swarmTextConfig: ComponentConfig = {
  slug: "swarm-text",
  name: "Swarm Text",
  category: "text",
  tags: ["swarm", "particles", "scatter", "assemble", "chaos"],
  componentPath: "app/meta/text/SwarmText/SwarmText.tsx",
  props: [
    {
      name: "texts",
      type: "string",
      default: "Developer, Designer, Philosopher, Physicist",
      description: "Array of words to rotate/morph through (comma-separated).",
    },
    {
      name: "prefix",
      type: "string",
      default: "I am a",
      description:
        "Static prefix text displayed in front of the dynamic words.",
    },
    {
      name: "delay",
      type: "number",
      default: 3000,
      min: 1000,
      max: 10000,
      step: 500,
      description:
        "Duration in milliseconds to display each word before swapping.",
    },
    {
      name: "fontSize",
      type: "number",
      default: 48,
      min: 24,
      max: 72,
      step: 2,
      description: "Font size of the dynamic text on the canvas (pixels).",
    },
    {
      name: "friction",
      type: "number",
      default: 0.85,
      min: 0.5,
      max: 0.98,
      step: 0.01,
      description: "Friction / damping coefficient for the particle movements.",
    },
    {
      name: "springStiffness",
      type: "number",
      default: 0.08,
      min: 0.01,
      max: 0.3,
      step: 0.01,
      description:
        "Spring stiffness factor pulling particles back to text target points.",
    },
    {
      name: "particleSize",
      type: "number",
      default: 1.8,
      min: 0.5,
      max: 5,
      step: 0.1,
      description: "Base radius of the rendered particles.",
    },
    {
      name: "step",
      type: "number",
      default: 3,
      min: 2,
      max: 6,
      step: 1,
      description:
        "Grid pixel sampling step. Lower values increase particle density but decrease performance.",
    },
    {
      name: "mouseRepel",
      type: "boolean",
      default: true,
      description:
        "Enables particle repulsion when hovering with the cursor or dragging.",
    },
    {
      name: "repelRadius",
      type: "number",
      default: 60,
      min: 20,
      max: 150,
      step: 5,
      description: "Radius of influence around the mouse in pixels.",
    },
    {
      name: "repelStrength",
      type: "number",
      default: 4.0,
      min: 0.5,
      max: 10.0,
      step: 0.5,
      description:
        "Repelling force factor pushing particles away from the mouse.",
    },
    {
      name: "textColor",
      type: "color",
      default: "#E8EAF0",
      description: "Hex or CSS color for the text particles.",
    },
    {
      name: "prefixColor",
      type: "color",
      default: "#9CA3AF",
      description: "Hex or CSS color for the prefix text.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Swarm",
      config: {
        texts: "Developer, Designer, Philosopher, Physicist",
        prefix: "I am a",
        fontSize: 48,
        textColor: "#E8EAF0",
        prefixColor: "#9CA3AF",
        friction: 0.85,
        springStiffness: 0.08,
        particleSize: 1.8,
        repelRadius: 60,
        repelStrength: 4.0,
        mouseRepel: true,
        step: 3,
      },
    },
    {
      id: "cyberpunk",
      label: "Cyberpunk Terminal",
      config: {
        texts: "ONLINE, ENCRYPTED, SECURE, SYSTEM",
        prefix: "Status:",
        fontSize: 40,
        textColor: "#10B981",
        prefixColor: "#6B7280",
        friction: 0.8,
        springStiffness: 0.12,
        particleSize: 2.2,
        repelRadius: 75,
        repelStrength: 6.0,
        mouseRepel: true,
        step: 3,
      },
    },
    {
      id: "sunset",
      label: "Warm Sunset",
      config: {
        texts: "Innovate, Inspire, Create, Connect",
        prefix: "Time to",
        fontSize: 44,
        textColor: "#F59E0B",
        prefixColor: "#EF4444",
        friction: 0.88,
        springStiffness: 0.06,
        particleSize: 1.5,
        repelRadius: 50,
        repelStrength: 3.0,
        mouseRepel: true,
        step: 3,
      },
    },
    {
      id: "fluid-cosmic",
      label: "Cosmic Nebula",
      config: {
        texts: "Space, Time, Quantum, Gravity",
        prefix: "Solving",
        fontSize: 52,
        textColor: "#8B5CF6",
        prefixColor: "#EC4899",
        friction: 0.92,
        springStiffness: 0.04,
        particleSize: 1.2,
        repelRadius: 100,
        repelStrength: 8.0,
        mouseRepel: true,
        step: 2,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "React Bytes",
          role: "Collection",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Open Source Techs",
      items: [
        {
          name: "React",
          role: "UI Library",
          url: "https://react.dev",
        },
        {
          name: "HTML5 Canvas",
          role: "Rendering API",
          url: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API",
        },
        {
          name: "Tailwind CSS",
          role: "Styling",
          url: "https://tailwindcss.com",
        },
      ],
    },
  ],
  staticProps: {
    prefixClassName: "text-xl font-medium md:text-2xl",
  },
};
