import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const stripeFlowConfig: ComponentConfig = {
  slug: "stripe-flow",
  name: "Stripe Flow",
  category: "background",
  tags: ["stripe", "flow", "lines", "gradient", "motion"],
  componentPath: "app/meta/background/StripeFlow/StripeFlow.tsx",
  showDemoByDefault: true,
  demoVariant: "card",
  description: "A customizable WebGL-powered background component that renders smooth, animated procedural stripe-like color flows with adjustable distortion, scale, radius, speed, and gradient colors while supporting overlay content.",
  npmPackageName: "@reactbytes/stripe-flow",
  version: "1.0.0",
  dependencies: {},
  peerDependencies: {
    react: "^18.0.0",
    "react-dom": "^18.0.0"
  },

  props: [
    {
      name: "seed",
      type: "number",
      default: 422,
      min: 0,
      max: 1000,
      step: 1,
      description: "Active seed for noise calculation.",
    },
    {
      name: "distortion",
      type: "number",
      default: 45.0,
      min: 10,
      max: 120,
      step: 1,
      description: "Multiplier controlling scalar field deformation.",
    },
    {
      name: "scale",
      type: "number",
      default: 0.008,
      min: 0.002,
      max: 0.025,
      step: 0.001,
      description: "Scale (density) of the Perlin noise texture grid.",
    },
    {
      name: "radius",
      type: "number",
      default: 0.8,
      min: 0.3,
      max: 1.5,
      step: 0.1,
      description: "Vignette circular boundary size multiplier.",
    },
    {
      name: "speed",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 2.0,
      step: 0.1,
      description: "Animation timeline speed multiplier.",
    },
    {
      name: "color1",
      type: "color",
      default: "#1a2a6c",
      description: "Base color.",
    },
    {
      name: "color2",
      type: "color",
      default: "#b21f1f",
      description: "Mid-wave color transition.",
    },
    {
      name: "color3",
      type: "color",
      default: "#fdbb2d",
      description: "Peak wave color.",
    },
    {
      name: "isPaused",
      type: "boolean",
      default: false,
      description: "Freeze the background wave flow animation.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Neo-Mint Wave (Default)",
      config: {
        seed: 422,
        distortion: 45.0,
        scale: 0.008,
        radius: 0.8,
        speed: 1.0,
        color1: "#00f2fe",
        color2: "#4facfe",
        color3: "#0052d4",
        isPaused: false,
      },
    },
    {
      id: "sunset",
      label: "Sunset Glow",
      config: {
        seed: 125,
        distortion: 75.0,
        scale: 0.012,
        radius: 1.1,
        speed: 1.2,
        color1: "#ff7b00",
        color2: "#ff0078",
        color3: "#420039",
        isPaused: false,
      },
    },
    {
      id: "brutalist",
      label: "Brutalist Monochrome",
      config: {
        seed: 888,
        distortion: 30.0,
        scale: 0.005,
        radius: 0.6,
        speed: 0.5,
        color1: "#0a0a0a",
        color2: "#3f3f3f",
        color3: "#d4d4d4",
        isPaused: false,
      },
    },
    {
      id: "acid",
      label: "Acid Flow",
      config: {
        seed: 941,
        distortion: 90.0,
        scale: 0.018,
        radius: 1.3,
        speed: 1.6,
        color1: "#ccff00",
        color2: "#00ff99",
        color3: "#000000",
        isPaused: false,
      },
    },
    {
      id: "cyberpunk",
      label: "Cyberpunk Neon",
      config: {
        seed: 521,
        distortion: 60.0,
        scale: 0.010,
        radius: 0.9,
        speed: 1.3,
        color1: "#fdf497",
        color2: "#fd5949",
        color3: "#d6249f",
        isPaused: false,
      },
    },
    {
      id: "abyss",
      label: "Ocean Abyss",
      config: {
        seed: 333,
        distortion: 50.0,
        scale: 0.007,
        radius: 0.75,
        speed: 0.8,
        color1: "#0f2027",
        color2: "#203a43",
        color3: "#2c5364",
        isPaused: false,
      },
    },
    {
      id: "aurora",
      label: "Northern Lights",
      config: {
        seed: 777,
        distortion: 65.0,
        scale: 0.009,
        radius: 1.0,
        speed: 1.1,
        color1: "#00c9ff",
        color2: "#92fe9d",
        color3: "#001f3f",
        isPaused: false,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Design & Development",
          url: "https://github.com/ChandruMIT-o/",
        },
      ],
    },
    {
      title: "Noise Physics Inspiration",
      items: [
        {
          name: "Gustavson 3D Noise",
          role: "WebGL Classic Perlin Noise",
          url: "https://github.com/stegu/webgl-noise",
        },
      ],
    },
  ],
};