import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const stripeFlowConfig: ComponentConfig = {
  slug: "stripe-flow",
  name: "Stripe Flow",
  category: "background",
  tags: ["stripe", "flow", "lines", "gradient", "motion"],
  componentPath: "app/meta/background/StripeFlow/StripeFlow.tsx",
  showDemoByDefault: true,
  demoVariant: "card",
  props: [
    {
      name: "seed",
      type: "number",
      default: 422,
      min: 0,
      max: 1000,
      step: 1,
      description: "Active seed for noise calculation.",
    },
    {
      name: "distortion",
      type: "number",
      default: 45.0,
      min: 10,
      max: 120,
      step: 1,
      description: "Multiplier controlling scalar field deformation.",
    },
    {
      name: "scale",
      type: "number",
      default: 0.008,
      min: 0.002,
      max: 0.025,
      step: 0.001,
      description: "Scale (density) of the Perlin noise texture grid.",
    },
    {
      name: "radius",
      type: "number",
      default: 0.8,
      min: 0.3,
      max: 1.5,
      step: 0.1,
      description: "Vignette circular boundary size multiplier.",
    },
    {
      name: "speed",
      type: "number",
      default: 1.0,
      min: 0.0,
      max: 2.0,
      step: 0.1,
      description: "Animation timeline speed multiplier.",
    },
    {
      name: "palette",
      type: "select",
      default: "vapor",
      options: [
        { id: "vapor", label: "Neo-Mint" },
        { id: "sunset", label: "Copper Glow" },
        { id: "slate", label: "Brutalist Gray" },
        { id: "acid", label: "Indigo Acid" },
        { id: "cyberpunk", label: "Cyberpunk Neon" },
        { id: "abyss", label: "Ocean Abyss" },
        { id: "aurora", label: "Northern Lights" },
      ],
      description: "Selected color preset mapping from PALETTES matrix.",
    },
    {
      name: "isPaused",
      type: "boolean",
      default: false,
      description: "Freeze the background wave flow animation.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Neo-Mint Wave (Default)",
      config: {
        seed: 422,
        distortion: 45.0,
        scale: 0.008,
        radius: 0.8,
        speed: 1.0,
        palette: "vapor",
        isPaused: false,
      },
    },
    {
      id: "sunset",
      label: "Sunset Glow",
      config: {
        seed: 125,
        distortion: 75.0,
        scale: 0.012,
        radius: 1.1,
        speed: 1.2,
        palette: "sunset",
        isPaused: false,
      },
    },
    {
      id: "brutalist",
      label: "Brutalist Monochrome",
      config: {
        seed: 888,
        distortion: 30.0,
        scale: 0.005,
        radius: 0.6,
        speed: 0.5,
        palette: "slate",
        isPaused: false,
      },
    },
    {
      id: "acid",
      label: "Acid Flow",
      config: {
        seed: 941,
        distortion: 90.0,
        scale: 0.018,
        radius: 1.3,
        speed: 1.6,
        palette: "acid",
        isPaused: false,
      },
    },
    {
      id: "cyberpunk",
      label: "Cyberpunk Neon",
      config: {
        seed: 521,
        distortion: 60.0,
        scale: 0.010,
        radius: 0.9,
        speed: 1.3,
        palette: "cyberpunk",
        isPaused: false,
      },
    },
    {
      id: "abyss",
      label: "Ocean Abyss",
      config: {
        seed: 333,
        distortion: 50.0,
        scale: 0.007,
        radius: 0.75,
        speed: 0.8,
        palette: "abyss",
        isPaused: false,
      },
    },
    {
      id: "aurora",
      label: "Northern Lights",
      config: {
        seed: 777,
        distortion: 65.0,
        scale: 0.009,
        radius: 1.0,
        speed: 1.1,
        palette: "aurora",
        isPaused: false,
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "React Bytes",
          role: "Styling & UI Assembly",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Noise Physics",
      items: [
        {
          name: "Gustavson 3D Noise",
          role: "WebGL Classic Perlin Noise",
          url: "https://github.com/stegu/webgl-noise",
        },
      ],
    },
  ],
};
