import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const stratumTextConfig: ComponentConfig = {
  slug: "stratum-text",
  name: "Stratum Text",
  category: "text",
  componentPath: "app/meta/text/StratumText/StratumText.tsx",
  props: [
    {
      name: "text",
      type: "string",
      default: "STRATA",
      description: "The word/text to render and animate.",
    },
    {
      name: "sliceCount",
      type: "number",
      default: 32,
      min: 4,
      max: 128,
      step: 2,
      description: "Number of slices text is divided into.",
    },
    {
      name: "stiffness",
      type: "number",
      default: 0.045,
      min: 0.005,
      max: 0.20,
      step: 0.005,
      description: "Hooke's spring stiffness constant.",
    },
    {
      name: "damping",
      type: "number",
      default: 0.82,
      min: 0.50,
      max: 0.99,
      step: 0.01,
      description: "Damping ratio of the spring physics.",
    },
    {
      name: "cutForce",
      type: "number",
      default: 0.45,
      min: 0.05,
      max: 2.0,
      step: 0.05,
      description: "Multiplier determining displacement force applied to slices.",
    },
    {
      name: "influenceRadius",
      type: "number",
      default: 90,
      min: 10,
      max: 300,
      step: 5,
      description: "Radial interaction distance around cursor.",
    },
    {
      name: "color",
      type: "color",
      default: "#ffffff",
      description: "Resting text color.",
    },
    {
      name: "wireframeColor",
      type: "color",
      default: "rgba(14, 165, 233, 0.35)",
      description: "Outline color showing architectural boundaries.",
    },
    {
      name: "bgColor",
      type: "color",
      default: "#08080a",
      description: "Background color of the canvas container.",
    },
  ],
  presets: [
    {
      id: "tectonic",
      label: "Tectonic Strata (Default)",
      config: {
        text: "STRATA",
        sliceCount: 32,
        stiffness: 0.045,
        damping: 0.82,
        cutForce: 0.45,
        influenceRadius: 90,
        color: "#ffffff",
        bgColor: "#08080a",
        wireframeColor: "rgba(14, 165, 233, 0.35)",
      },
    },
    {
      id: "glitch",
      label: "Cyber Glitch",
      config: {
        text: "GLITCH",
        sliceCount: 64,
        stiffness: 0.09,
        damping: 0.75,
        cutForce: 0.8,
        influenceRadius: 120,
        color: "#39ff14",
        bgColor: "#050505",
        wireframeColor: "rgba(255, 0, 128, 0.6)",
      },
    },
    {
      id: "liquid",
      label: "Slow Liquid",
      config: {
        text: "LIQUID",
        sliceCount: 16,
        stiffness: 0.015,
        damping: 0.95,
        cutForce: 0.2,
        influenceRadius: 150,
        color: "#00f0ff",
        bgColor: "#000814",
        wireframeColor: "rgba(0, 240, 255, 0.2)",
      },
    },
  ],
  credits: [
    {
      title: "Component Source",
      items: [
        {
          name: "React Bytes",
          role: "Author",
          url: "https://reactbytes.dev",
        },
      ],
    },
    {
      title: "Open Source Libraries",
      items: [
        {
          name: "React",
          role: "UI Framework",
          url: "https://react.dev",
        },
      ],
    },
  ],
  staticProps: {},
};
