import { ComponentConfig } from "@/app/registry/ComponentDatabase";

const DEFAULT_ITEMS = [
  { id: "1", type: "text" as const, content: "SYSTEM" },
  {
    id: "2",
    type: "image" as const,
    content: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
    title: "NEURAL NET",
    subtitle: "v2.0.4",
  },
  { id: "3", type: "card" as const, content: "BRUTAL", title: "INTERFACE", coords: [45, 92] as [number, number] },
  { id: "4", type: "text" as const, content: "DESIGN" },
  {
    id: "5",
    type: "image" as const,
    content: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop",
    title: "CYBER CORE",
    subtitle: "Online",
  },
  { id: "6", type: "card" as const, content: "MOTION", title: "DYNAMICS", coords: [12, 33] as [number, number] },
];

export const voidCarouselConfig: ComponentConfig = {
  slug: "void-carousel",
  name: "Void Carousel",
  category: "carousel",
  componentPath: "app/meta/carousel/VoidCarousel/VoidCarousel.tsx",
  containerClassName: "h-[500px] w-full rounded-[18px] border border-rb-neutral-4/50 overflow-hidden relative isolate bg-black flex flex-col !p-0",
  staticProps: {
    items: DEFAULT_ITEMS,
    enableNoise: false,
  },
  props: [
    {
      name: "zGap",
      type: "number",
      default: 600,
      min: 200,
      max: 1500,
      step: 50,
      description: "Distance between items in Z space.",
    },
    {
      name: "speedFactor",
      type: "number",
      default: 2.5,
      min: 0.5,
      max: 10.0,
      step: 0.5,
      description: "Scroll speed multiplier.",
    },
    {
      name: "warpFactor",
      type: "number",
      default: 2.0,
      min: 0,
      max: 5,
      step: 0.5,
      description: "Warp effect intensity.",
    },
    {
      name: "basePerspective",
      type: "number",
      default: 800,
      min: 300,
      max: 1500,
      step: 100,
      description: "Base 3D perspective.",
    },
    {
      name: "lerpFactor",
      type: "number",
      default: 0.08,
      min: 0.01,
      max: 0.3,
      step: 0.01,
      description: "Lerp momentum factor.",
    },
    {
      name: "activeZ",
      type: "number",
      default: 0,
      min: -500,
      max: 500,
      step: 10,
      description: "Z position where items focus and snap.",
    },
    {
      name: "opacityFade",
      type: "number",
      default: 400,
      min: 100,
      max: 1000,
      step: 50,
      description: "Distance over which items fade out past activeZ.",
    },
    {
      name: "enableSnap",
      type: "boolean",
      default: false,
      description: "Enable magnetic snapping.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Default Style",
      config: {
        zGap: 600,
        speedFactor: 2.5,
        lerpFactor: 0.08,
        warpFactor: 2.0,
        basePerspective: 800,
        enableSnap: false,
        activeZ: 0,
        opacityFade: 400,
      },
    },
    {
      id: "snappy",
      label: "Snappy",
      config: {
        zGap: 800,
        speedFactor: 3.0,
        lerpFactor: 0.1,
        warpFactor: 1.5,
        basePerspective: 600,
        enableSnap: true,
        activeZ: 0,
        opacityFade: 400,
      },
    },
    {
      id: "warp",
      label: "Warp Speed",
      config: {
        zGap: 1200,
        speedFactor: 5.0,
        lerpFactor: 0.05,
        warpFactor: 4.0,
        basePerspective: 1000,
        enableSnap: false,
        activeZ: 0,
        opacityFade: 400,
      },
    },
    {
      id: "smooth",
      label: "Smooth Float",
      config: {
        zGap: 400,
        speedFactor: 1.5,
        lerpFactor: 0.02,
        warpFactor: 0.5,
        basePerspective: 1200,
        enableSnap: false,
        activeZ: 0,
        opacityFade: 400,
      },
    },
    {
      id: "tight",
      label: "Tight Tunnel",
      config: {
        zGap: 300,
        speedFactor: 2.0,
        lerpFactor: 0.1,
        warpFactor: 1.0,
        basePerspective: 400,
        enableSnap: true,
        activeZ: 0,
        opacityFade: 400,
      },
    },
  ],
  credits: [
    {
      title: "Developer",
      items: [
        {
          name: "React Bytes",
          role: "Component Creation",
          url: "https://github.com/ChandruMIT-o",
        },
      ],
    },
    {
      title: "Project Author",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Creator & Lead Designer",
          url: "https://github.com/ChandruMIT-o",
        },
      ],
    },
    {
      title: "Core Stack",
      items: [
        {
          name: "Next.js 16",
          role: "Framework",
          url: "https://nextjs.org",
        },
        {
          name: "Tailwind CSS v4",
          role: "Styling Engine",
          url: "https://tailwindcss.com",
        },
        {
          name: "Framer Motion",
          role: "Animation Library",
          url: "https://framer.com/motion",
        },
      ],
    },
  ],
};
