import { ComponentConfig } from "@/app/registry/ComponentDatabase";

export const listCarouselConfig: ComponentConfig = {
  slug: "list-carousel",
  name: "List Carousel",
  category: "carousel",
  tags: ["carousel", "list", "scroll", "items", "smooth-scroll", "mobile-optimized", "customizable"],
  componentPath: "app/meta/carousel/ListCarousel/ListCarousel.tsx",
  npmPackageName: "@reactbytes/list-carousel",
  version: "1.0.0",
  dependencies: {},
  peerDependencies: {
    react: "^19.0.0",
    "react-dom": "^19.0.0",
  },
  containerClassName:
    "h-[500px] md:h-[650px] w-full rounded-xl border border-rb-neutral-4 shadow-2xl !p-0 overflow-hidden",
  props: [
    {
      name: "defaultBg",
      type: "string",
      default: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
      description: "The background image displayed when no item is hovered.",
    },
    {
      name: "scrollLerpFactor",
      type: "number",
      default: 0.09,
      min: 0.01,
      max: 1.0,
      step: 0.01,
      description: "Interpolation speed factor for vertical smooth scrolling (0.01 - 1). Lower means more lag/damping.",
    },
    {
      name: "cursorLerpFactor",
      type: "number",
      default: 0.12,
      min: 0.01,
      max: 1.0,
      step: 0.01,
      description: "Interpolation speed factor for the custom cursor image lag preview (0.01 - 1).",
    },
    {
      name: "maxCursorRotation",
      type: "number",
      default: 10,
      min: 0,
      max: 45,
      step: 1,
      description: "The maximum angle variation (in degrees) for the image preview frame tilt when items are hovered.",
    },
    {
      name: "enableNoise",
      type: "boolean",
      default: true,
      description: "Toggles the animated cinematic SVG grain noise overlay framework.",
    },
    {
      name: "noiseOpacity",
      type: "number",
      default: 0.18,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      description: "The blending opacity of the SVG grain element.",
    },
    // --- Value-based Background Atmosphere Props ---
    {
      name: "idleOpacity",
      type: "number",
      default: 0.2,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      description: "Opacity of background atmosphere when no item is hovered.",
    },
    {
      name: "idleBlur",
      type: "number",
      default: 4,
      min: 0,
      max: 30,
      step: 1,
      description: "Blur radius of background atmosphere when no item is hovered (pixels).",
    },
    {
      name: "idleScale",
      type: "number",
      default: 1.0,
      min: 0.8,
      max: 1.5,
      step: 0.05,
      description: "Scale of background atmosphere when no item is hovered.",
    },
    {
      name: "idleGrayscale",
      type: "boolean",
      default: false,
      description: "Enable grayscale effect on background atmosphere when no item is hovered.",
    },
    {
      name: "hoverOpacity",
      type: "number",
      default: 0.5,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      description: "Opacity of background atmosphere when an item is hovered.",
    },
    {
      name: "hoverBlur",
      type: "number",
      default: 0,
      min: 0,
      max: 30,
      step: 1,
      description: "Blur radius of background atmosphere when an item is hovered (pixels).",
    },
    {
      name: "hoverScale",
      type: "number",
      default: 1.0,
      min: 0.8,
      max: 1.5,
      step: 0.05,
      description: "Scale of background atmosphere when an item is hovered.",
    },
    {
      name: "hoverGrayscale",
      type: "boolean",
      default: false,
      description: "Enable grayscale effect on background atmosphere when an item is hovered.",
    },
    // --- Value-based Font and Style Props ---
    {
      name: "titleSize",
      type: "select",
      default: "md",
      options: [
        { id: "xs", label: "Extra Small" },
        { id: "sm", label: "Small" },
        { id: "md", label: "Medium" },
        { id: "lg", label: "Large" },
        { id: "xl", label: "Extra Large" },
      ],
      description: "Responsive text size of list items titles.",
    },
    {
      name: "titleWeight",
      type: "select",
      default: "bold",
      options: [
        { id: "light", label: "Light" },
        { id: "normal", label: "Normal" },
        { id: "medium", label: "Medium" },
        { id: "semibold", label: "Semibold" },
        { id: "bold", label: "Bold" },
        { id: "black", label: "Black" },
      ],
      description: "Font weight of list items titles.",
    },
    {
      name: "titleTracking",
      type: "select",
      default: "tight",
      options: [
        { id: "tighter", label: "Tighter" },
        { id: "tight", label: "Tight" },
        { id: "normal", label: "Normal" },
        { id: "wide", label: "Wide" },
        { id: "wider", label: "Wider" },
        { id: "widest", label: "Widest" },
      ],
      description: "Tracking/letter spacing of list items titles.",
    },
    {
      name: "titleTransform",
      type: "select",
      default: "none",
      options: [
        { id: "none", label: "Normal Case" },
        { id: "uppercase", label: "Uppercase" },
        { id: "lowercase", label: "Lowercase" },
        { id: "capitalize", label: "Capitalize" },
      ],
      description: "Text casing casing for list items titles.",
    },
    {
      name: "titleStyle",
      type: "select",
      default: "normal",
      options: [
        { id: "normal", label: "Normal" },
        { id: "italic", label: "Italic" },
      ],
      description: "Text style (normal or italic) of list items titles.",
    },
    {
      name: "titleColor",
      type: "color",
      default: "#eaeaea",
      description: "Base text color of list items titles.",
    },
    {
      name: "titleHoverColor",
      type: "color",
      default: "#eaeaea",
      description: "Hover text color of list items titles.",
    },
    {
      name: "indexSize",
      type: "select",
      default: "sm",
      options: [
        { id: "xxs", label: "Tiny" },
        { id: "xs", label: "Extra Small" },
        { id: "sm", label: "Small" },
        { id: "md", label: "Medium" },
      ],
      description: "Size of list item index prefixes.",
    },
    {
      name: "indexFont",
      type: "select",
      default: "mono",
      options: [
        { id: "mono", label: "Monospace" },
        { id: "sans", label: "Sans Serif" },
        { id: "serif", label: "Serif" },
      ],
      description: "Font family of list item index prefixes.",
    },
    {
      name: "indexTracking",
      type: "select",
      default: "wider",
      options: [
        { id: "normal", label: "Normal" },
        { id: "wide", label: "Wide" },
        { id: "wider", label: "Wider" },
        { id: "widest", label: "Widest" },
      ],
      description: "Letter spacing of list item index prefixes.",
    },
    {
      name: "enableIndexBg",
      type: "boolean",
      default: false,
      description: "Show background box for list item index prefixes.",
    },
    {
      name: "indexOpacity",
      type: "number",
      default: 0.4,
      min: 0.1,
      max: 1.0,
      step: 0.05,
      description: "Base opacity of list item index prefixes.",
    },
    {
      name: "paddingY",
      type: "number",
      default: 15,
      min: 5,
      max: 40,
      step: 1,
      description: "Top and bottom vertical padding room in vh units.",
    },
  ],
  presets: [
    {
      id: "default",
      label: "Minimalist Architecture",
      config: {
        defaultBg: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
        scrollLerpFactor: 0.09,
        cursorLerpFactor: 0.12,
        maxCursorRotation: 10,
        enableNoise: true,
        noiseOpacity: 0.18,
        idleOpacity: 0.2,
        idleBlur: 4,
        idleScale: 1.0,
        idleGrayscale: false,
        hoverOpacity: 0.5,
        hoverBlur: 0,
        hoverScale: 1.0,
        hoverGrayscale: false,
        titleSize: "md",
        titleWeight: "bold",
        titleTracking: "tight",
        titleTransform: "none",
        titleStyle: "normal",
        titleColor: "#eaeaea",
        titleHoverColor: "#eaeaea",
        indexSize: "sm",
        indexFont: "mono",
        indexTracking: "wider",
        enableIndexBg: false,
        indexOpacity: 0.4,
        paddingY: 15,
      },
    },
    {
      id: "brutalist-raw",
      label: "Brutalist Monolith",
      config: {
        defaultBg: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
        scrollLerpFactor: 0.16,
        cursorLerpFactor: 0.22,
        maxCursorRotation: 0,
        enableNoise: true,
        noiseOpacity: 0.35,
        idleOpacity: 0.3,
        idleBlur: 0,
        idleScale: 1.0,
        idleGrayscale: true,
        hoverOpacity: 0.75,
        hoverBlur: 0,
        hoverScale: 1.0,
        hoverGrayscale: false,
        titleSize: "sm",
        titleWeight: "black",
        titleTracking: "tighter",
        titleTransform: "uppercase",
        titleStyle: "normal",
        titleColor: "#eaeaea",
        titleHoverColor: "#eaeaea",
        indexSize: "xs",
        indexFont: "mono",
        indexTracking: "widest",
        enableIndexBg: true,
        indexOpacity: 0.4,
        paddingY: 10,
      },
    },
    {
      id: "deep-midnight",
      label: "Deep Midnight",
      config: {
        defaultBg: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
        scrollLerpFactor: 0.04,
        cursorLerpFactor: 0.06,
        maxCursorRotation: 20,
        enableNoise: false,
        noiseOpacity: 0.0,
        idleOpacity: 0.1,
        idleBlur: 12,
        idleScale: 1.1,
        idleGrayscale: false,
        hoverOpacity: 0.4,
        hoverBlur: 2,
        hoverScale: 1.05,
        hoverGrayscale: false,
        titleSize: "xs",
        titleWeight: "light",
        titleTracking: "widest",
        titleTransform: "none",
        titleStyle: "italic",
        titleColor: "#d4d4d4",
        titleHoverColor: "#eaeaea",
        indexSize: "xxs",
        indexFont: "serif",
        indexTracking: "normal",
        enableIndexBg: false,
        indexOpacity: 0.4,
        paddingY: 25,
      },
    },
  ],
  credits: [
    {
      title: "Project Author",
      items: [
        {
          name: "ChandruMIT-o",
          role: "Creator & Lead Designer",
          url: "https://github.com/ChandruMIT-o",
        },
      ],
    },
  ],
};